services:
  observatorio:
    build: .

    container_name: observatorio

    volumes:
      - .:/app
      - ./output:/app/output
      - ./logs:/app/logs

    command: python run_dev.py

    restart: unless-stopped

    stdin_open: false
    tty: false