# -*- coding: utf-8 -*-
"""ALAJUELA DIGITAL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Us7l-rPaNtz0dTB7xXg3Tm1lutbuwfRh
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd
import re
import time
from datetime import datetime

# -------------------------------------------------------------
# CONFIGURACIÓN
# -------------------------------------------------------------
BASE_URL = 'https://alajueladigital.net/'

HEADERS = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'}
DELAY = 1.5

# -------------------------------------------------------------
# FUNCIONES
# -------------------------------------------------------------
def get_soup(url, session):
    """Petición HTTP → BeautifulSoup. Retorna None si falla."""
    try:
        response = session.get(url, timeout=10)
        response.raise_for_status()
        return BeautifulSoup(response.text, 'html.parser')
    except requests.RequestException as e:
        print(f"  Error: {url} -> {e}")
        return None

def clean_text(text):
    """Elimina espacios y saltos de línea extra."""
    return re.sub(r'\s+', ' ', text).strip() if text else ""

def extract_article_data(soup):
    """
    Extrae título, fecha, sección y contenido del artículo.
    Estructura HTML de alajueladigital.net:
      - Título:    <h1 class="title">
      - Fecha:     <span class="mg-blog-date"> → "MAR 21, 2026"
      - Sección:   <div class="mg-blog-category"><a>
      - Contenido: <article class="small single">
    """
    # Título
    title_tag = soup.find('h1', class_='title')
    title = clean_text(title_tag.get_text()) if title_tag else "Sin titulo"

    # Fecha — formato original "MAR 21, 2026" → convertir a YYYY-MM-DD
    date = "Sin fecha"
    date_span = soup.find('span', class_='mg-blog-date')
    if date_span:
        date_raw = clean_text(date_span.get_text())
        try:
            date = datetime.strptime(date_raw, "%b %d, %Y").strftime("%Y-%m-%d")
        except:
            date = date_raw

    # Sección real del artículo
    section = "sin-seccion"
    category_div = soup.find('div', class_='mg-blog-category')
    if category_div:
        a_tag = category_div.find('a')
        if a_tag:
            section = clean_text(a_tag.get_text()).lower()
            section = section.replace('á','a').replace('é','e').replace('í','i').replace('ó','o').replace('ú','u').replace(' ','-')

    # Contenido
    content = "Contenido no encontrado"
    article_body = soup.find('article', class_=re.compile(r'small single'))
    if article_body:
        for tag in article_body.find_all(['script', 'style', 'iframe', 'figure', 'aside']):
            tag.decompose()
        content = clean_text(article_body.get_text())

    return title, date, section, content

# -------------------------------------------------------------
# SCRAPING PRINCIPAL
# -------------------------------------------------------------
data = []

with requests.Session() as session:
    session.headers.update(HEADERS)

    print(f"Leyendo pagina principal: {BASE_URL}\n")
    main_soup = get_soup(BASE_URL, session)

    if main_soup is None:
        print("No se pudo acceder a la pagina principal.")
    else:
        # Extraer links únicos desde los h4 del listado
        links = []
        for h4 in main_soup.find_all('h4'):
            a = h4.find('a', href=True)
            if a and a['href'] not in links:
                links.append(a['href'])

        print(f"{len(links)} articulos encontrados.\n")

        for i, link in enumerate(links, 1):
            print(f"  [{i}/{len(links)}] {link.split('/')[-2][:55]}...")
            time.sleep(DELAY)

            article_soup = get_soup(link, session)
            if article_soup:
                title, date, section, content = extract_article_data(article_soup)
            else:
                title, date, section, content = "Error", "Error", "sin-seccion", "Error al recuperar"

            data.append({
                'source':           'alajueladigital',
                'url':              link,
                'title':            title,
                'publication_date': date,
                'scraping_date':    datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
                'section':          section,
                'full_text':        content,
                'language':         'es'
            })

# -------------------------------------------------------------
# RESULTADO FINAL — sin duplicados por URL
# -------------------------------------------------------------
df4 = pd.DataFrame(data).drop_duplicates(subset='url')
print(f"\nDataFrame: {len(df4)} filas x {len(df4.columns)} columnas")
df4.head(8)

df4.to_csv('alajueladigital.csv',
           index=False,          # Sin índice adicional
           encoding='utf-8',     # UTF-8
           sep=',',              # Separador por coma
           na_rep='NULL')        # Nulos como NULL real

try:
    from google.colab import files
except ImportError:
    files = None
files.download('alajueladigital.csv')