# -*- coding: utf-8 -*-
"""amprensa.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YvAC03H_eIiAbWLTs31TtScUZ-vqHrzk
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd
import time
import re
from datetime import datetime

# --- Configuración ---
BASE_URL = 'https://www.amprensa.com'
SECTIONS = {
    'nacionales': 'https://www.amprensa.com/categorias/nacionales',
    'internacionales': 'https://www.amprensa.com/categorias/internacionales',
    'deportes': 'https://www.amprensa.com/categorias/am-deportes',
    'sucesos': 'https://www.amprensa.com/categorias/sucesos',
    'espectaculos': 'https://www.amprensa.com/categorias/espectaculos',
    'cartago': 'https://www.amprensa.com/categorias/am-prensa-cartago',
    'tecnologia': 'https://www.amprensa.com/categorias/tecnologia',
    'viral': 'https://www.amprensa.com/categorias/viral'
}
HEADERS = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 '
                  '(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
}
DELAY = 1.0

def get_soup(url, session):
    """Petición HTTP → BeautifulSoup. Retorna None si falla."""
    try:
        response = session.get(url, timeout=10)
        response.raise_for_status()
        return BeautifulSoup(response.text, 'html.parser')
    except requests.RequestException as e:
        print(f"  ⚠️  Error: {url} → {e}")
        return None

def clean_text(text):
    """Elimina espacios/saltos de línea extra."""
    return re.sub(r'\s+', ' ', text).strip() if text else ""

def get_section_from_url(url):
    """Extrae la sección desde la URL."""
    url_lower = url.lower()
    if '/categorias/nacionales' in url_lower or 'nacionales' in url_lower:
        return 'nacionales'
    elif '/categorias/internacionales' in url_lower:
        return 'internacionales'
    elif '/categorias/am-deportes' in url_lower or 'deportes' in url_lower:
        return 'deportes'
    elif '/categorias/sucesos' in url_lower:
        return 'sucesos'
    elif '/categorias/espectaculos' in url_lower:
        return 'espectaculos'
    elif '/categorias/am-prensa-cartago' in url_lower or 'cartago' in url_lower:
        return 'cartago'
    elif '/categorias/tecnologia' in url_lower:
        return 'tecnologia'
    elif '/categorias/viral' in url_lower:
        return 'viral'
    elif '/categorias/ultima-hora' in url_lower:
        return 'ultima-hora'
    return 'general'

def extract_article_data(soup, url):
    """
    Extrae título, fecha, autor y contenido desde la página interna del artículo.
    Selectores basados en la estructura real de amprensa.com
    """
    # --- Título ---
    # Buscar en h1 o en div.title-left h3
    title = "Sin título"
    title_tag = soup.find('h1')
    if title_tag:
        title = clean_text(title_tag.get_text())
    else:
        title_div = soup.find('div', class_='title-left')
        if title_div:
            h3 = title_div.find('h3')
            if h3:
                title = clean_text(h3.get_text())

    # --- Categoría ---
    category = "Sin categoría"
    cat_tag = soup.find('a', class_=lambda x: x and 'label-' in x)
    if cat_tag:
        category = clean_text(cat_tag.get_text())
    else:
        category = get_section_from_url(url)

    # --- Autor ---
    # <div class="post-meta-author"><i class="fa fa-user"></i><a href="#">Autor</a></div>
    author = "Sin autor"
    author_div = soup.find('div', class_='post-meta-author')
    if author_div:
        author_link = author_div.find('a')
        if author_link:
            author = clean_text(author_link.get_text())
        else:
            # Si no hay link, buscar texto después del icono
            author = clean_text(author_div.get_text())
            author = author.replace('', '').strip()  # Eliminar icono si quedó

    # --- Fecha ---
    # <div class="post-meta-date"><i class="fa fa-calendar"></i>13 de Abril de 2026</div>
    date = "Sin fecha"
    date_div = soup.find('div', class_='post-meta-date')
    if date_div:
        date = clean_text(date_div.get_text())
    else:
        # Buscar en small.day
        date_small = soup.find('small', class_='day')
        if date_small:
            date = clean_text(date_small.get_text())

    # --- Contenido ---
    content = "Contenido no encontrado"

    # Buscar en el artículo principal o en item-content
    content_div = soup.find('div', class_='entry-content')
    if not content_div:
        content_div = soup.find('article')
    if not content_div:
        content_div = soup.find('div', class_='post-content')
    if not content_div:
        # Buscar todos los párrafos dentro del body principal
        main_section = soup.find('section', id='main-section')
        if main_section:
            content_div = main_section

    if content_div:
        # Eliminar elementos no deseados
        for tag in content_div.find_all(['script', 'style', 'iframe', 'ins', 'figure', 'nav', 'header', 'footer']):
            tag.decompose()
        for ad in content_div.find_all('div', class_=lambda x: x and ('ad' in x.lower() or 'sidebar' in x.lower())):
            ad.decompose()

        # Extraer párrafos
        paragraphs = content_div.find_all('p')
        if paragraphs:
            content = ' '.join([clean_text(p.get_text()) for p in paragraphs if p.get_text().strip() and len(p.get_text().strip()) > 20])

        if not content or content == "Contenido no encontrado":
            content = clean_text(content_div.get_text())[:2000]

    return title, author, date, content, category

def get_article_links(soup):
    """Extrae todos los enlaces de artículos de una página."""
    links = []

    # Buscar enlaces con patrón /2026/ o /2025/ (años)
    for a_tag in soup.find_all('a', href=True):
        href = a_tag['href']

        # Filtrar enlaces de noticias (formato: /2026/04/slug)
        if re.search(r'/20\d{2}/\d{2}/', href):
            if href.startswith('/'):
                href = BASE_URL + href
            if 'amprensa.com' in href and href not in links:
                links.append(href)

    return links

# -------------------------------------------------------
# PASO 1: Leer página principal y secciones → extraer enlaces
# -------------------------------------------------------
data = []
all_links = []

with requests.Session() as session:
    session.headers.update(HEADERS)

    print("=" * 70)
    print("📰 WEB SCRAPING - AM PRENSA")
    print("=" * 70)

    # Primero la página principal
    print(f"\n📂 Leyendo: PÁGINA PRINCIPAL")
    main_soup = get_soup(BASE_URL, session)

    if main_soup:
        links = get_article_links(main_soup)
        print(f"   ✅ {len(links)} enlaces encontrados")
        all_links.extend(links)

    time.sleep(DELAY)

    # Luego las secciones
    for section_name, section_url in SECTIONS.items():
        print(f"\n📂 Leyendo sección: {section_name.upper()}")
        section_soup = get_soup(section_url, session)

        if section_soup:
            links = get_article_links(section_soup)
            print(f"   ✅ {len(links)} enlaces encontrados")
            all_links.extend(links)
        else:
            print(f"   ⚠️ Sección no accesible, continuando...")

        time.sleep(DELAY)

    # Eliminar duplicados
    all_links = list(set(all_links))
    print(f"\n🔗 Total de enlaces únicos: {len(all_links)}")

    # -------------------------------------------------------
    # PASO 2: Entrar a cada enlace y extraer datos del artículo
    # -------------------------------------------------------
    if len(all_links) > 0:
        print("\n" + "=" * 70)
        print(f"📰 Extrayendo {len(all_links)} artículos...")
        print("=" * 70 + "\n")

        for i, link in enumerate(all_links, 1):
            slug = link.rstrip('/').split('/')[-1][:50]
            print(f"  [{i}/{len(all_links)}] Procesando: {slug}...")

            time.sleep(DELAY)

            article_soup = get_soup(link, session)
            if article_soup:
                title, author, date, content, section = extract_article_data(article_soup, link)
            else:
                title, author, date, content, section = "Error", "Error", "Error", "Error al recuperar", "error"

            data.append({
                'source':           'amprensa',
                'url':              link,
                'title':            title,
                'author':           author,
                'publication_date': date,
                'scraping_date':    datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
                'section':          section,
                'full_text':        content,
                'language':         'es'
            })
    else:
        print("\n⚠️ No se encontraron enlaces.")

# -------------------------------------------------------
# PASO 3: DataFrame final
# -------------------------------------------------------
df = pd.DataFrame(data)

print("\n" + "=" * 70)
pd.set_option('display.max_colwidth', 60)
print(f"📊 DataFrame: {len(df)} filas × {len(df.columns)} columnas")
print("=" * 70)

if len(df) > 0:
    print("\n📈 Artículos por sección:")
    print(df['section'].value_counts())

    print("\n📋 Primeros artículos:")
    display(df[['title', 'author', 'publication_date', 'section']].head(10))

# --- Exportar a CSV ---
df.to_csv('amprensa.csv', index=False, encoding='utf-8-sig')
print(f"\n💾 Archivo guardado: amprensa.csv")

try:
    from google.colab import files
except ImportError:
    files = None
files.download('amprensa.csv')

df.to_csv('amprensa.csv', index=False, encoding='utf-8-sig')
from google.colab import files
files.download('amprensa.csv')