# -*- coding: utf-8 -*-
"""CRC 89.1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TUzG7AfYDN0E2VjvDN3LulBOpFvdNGTn
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd
import time
import re
from datetime import datetime

# --- Configuración ---
BASE_URL = 'https://crc891.com'
SECTIONS = {
    'nacionales': 'https://crc891.com/categoria/nacionales/',
    'mundo': 'https://crc891.com/categoria/mundo/',
    'tecnologia': 'https://crc891.com/categoria/tecnologia/',
    'deportes': 'https://crc891.com/categoria/deportes/',
    'entretenimiento': 'https://crc891.com/categoria/entretenimiento/'
}
HEADERS = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 '
                  '(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
}
DELAY = 1.0

def get_soup(url, session):
    """Petición HTTP → BeautifulSoup. Retorna None si falla."""
    try:
        response = session.get(url, timeout=10)
        response.raise_for_status()
        return BeautifulSoup(response.text, 'html.parser')
    except requests.RequestException as e:
        print(f"  ⚠️  Error: {url} → {e}")
        return None

def clean_text(text):
    """Elimina espacios/saltos de línea extra."""
    return re.sub(r'\s+', ' ', text).strip() if text else ""

def get_section_from_url(url):
    """Extrae la sección desde la URL."""
    if '/nacionales/' in url:
        return 'nacionales'
    elif '/mundo/' in url:
        return 'mundo'
    elif '/tecnologia/' in url:
        return 'tecnologia'
    elif '/deportes/' in url:
        return 'deportes'
    elif '/entretenimiento/' in url:
        return 'entretenimiento'
    elif '/seguridad/' in url:
        return 'seguridad'
    return 'general'

def extract_article_data(soup, url):
    """
    Extrae título, fecha, autor y contenido desde la página interna del artículo.
    Selectores basados en la estructura real de crc891.com
    """
    # --- Título ---
    # <h1 class="post-title entry-title">
    title_tag = soup.find('h1', class_='post-title')
    title = clean_text(title_tag.get_text()) if title_tag else "Sin título"

    # --- Categoría ---
    # <span class="post-cat-wrap">
    category_tag = soup.find('span', class_='post-cat-wrap')
    if category_tag:
        category = clean_text(category_tag.get_text())
    else:
        category = get_section_from_url(url)

    # --- Autor ---
    # Buscar en div.single-post-meta o a.author-name
    author = "Sin autor"
    author_tag = soup.find('a', class_='author-name')
    if author_tag:
        author = clean_text(author_tag.get_text())
    else:
        meta_div = soup.find('div', class_='single-post-meta')
        if meta_div:
            author_link = meta_div.find('a')
            if author_link:
                author = clean_text(author_link.get_text())

    # --- Fecha ---
    # <span class="date meta-item">
    date = "Sin fecha"
    date_tag = soup.find('span', class_='date')
    if date_tag:
        date = clean_text(date_tag.get_text())
    else:
        time_tag = soup.find('time')
        if time_tag:
            date = clean_text(time_tag.get_text())

    # --- Contenido ---
    # <div class="entry-content entry clearfix">
    content = "Contenido no encontrado"
    content_div = soup.find('div', class_='entry-content')

    if content_div:
        # Eliminar scripts, estilos, iframes y anuncios
        for tag in content_div.find_all(['script', 'style', 'iframe', 'ins', 'figure']):
            tag.decompose()
        for ad in content_div.find_all('div', class_=lambda x: x and 'code-block' in x):
            ad.decompose()

        # Extraer solo párrafos <p>
        paragraphs = content_div.find_all('p')
        if paragraphs:
            content = ' '.join([clean_text(p.get_text()) for p in paragraphs if p.get_text().strip()])
        else:
            content = clean_text(content_div.get_text())

    return title, author, date, content, category

def get_article_links(soup):
    """Extrae todos los enlaces de artículos de una página de sección."""
    links = []

    # Método 1: Buscar en artículos
    for article in soup.find_all('article'):
        a_tag = article.find('a', href=True)
        if a_tag and '/202' in a_tag['href']:
            href = a_tag['href']
            if href not in links:
                links.append(href)

    # Método 2: Buscar en h2.post-title
    for h2 in soup.find_all('h2', class_='post-title'):
        a_tag = h2.find('a', href=True)
        if a_tag:
            href = a_tag['href']
            if href not in links:
                links.append(href)

    return links

# -------------------------------------------------------
# PASO 1: Leer listados de cada sección → extraer enlaces
# -------------------------------------------------------
data = []
all_links = []

with requests.Session() as session:
    session.headers.update(HEADERS)

    print("=" * 70)
    print("📰 WEB SCRAPING - CRC 891")
    print("=" * 70)

    # Obtener enlaces de todas las secciones
    for section_name, section_url in SECTIONS.items():
        print(f"\n📂 Leyendo sección: {section_name.upper()}")
        section_soup = get_soup(section_url, session)

        if section_soup:
            links = get_article_links(section_soup)
            print(f"   ✅ {len(links)} enlaces encontrados")
            all_links.extend(links)
        else:
            print(f"   ❌ Error al acceder a {section_name}")

        time.sleep(DELAY)

    # Eliminar duplicados
    all_links = list(set(all_links))
    print(f"\n🔗 Total de enlaces únicos: {len(all_links)}")

    # -------------------------------------------------------
    # PASO 2: Entrar a cada enlace y extraer datos del artículo
    # -------------------------------------------------------
    print("\n" + "=" * 70)
    print(f"📰 Extrayendo {len(all_links)} artículos...")
    print("=" * 70 + "\n")

    for i, link in enumerate(all_links, 1):
        # Extraer slug para mostrar progreso
        slug = link.rstrip('/').split('/')[-1][:50]
        print(f"  [{i}/{len(all_links)}] Procesando: {slug}...")

        time.sleep(DELAY)

        article_soup = get_soup(link, session)
        if article_soup:
            title, author, date, content, section = extract_article_data(article_soup, link)
        else:
            title, author, date, content, section = "Error", "Error", "Error", "Error al recuperar", "error"

        data.append({
            'source':           'crc891',
            'url':              link,
            'title':            title,
            'author':           author,
            'publication_date': date,
            'scraping_date':    datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
            'section':          section,
            'full_text':        content,
            'language':         'es'
        })

# -------------------------------------------------------
# PASO 3: DataFrame final
# -------------------------------------------------------
df = pd.DataFrame(data)

print("\n" + "=" * 70)
pd.set_option('display.max_colwidth', 60)
print(f"📊 DataFrame: {len(df)} filas × {len(df.columns)} columnas")
print("=" * 70)

# Mostrar resumen por sección
print("\n📈 Artículos por sección:")
print(df['section'].value_counts())

# Mostrar primeras filas
print("\n📋 Primeros artículos:")
df[['title', 'author', 'publication_date', 'section']].head(10)

df.to_csv('crc891.csv', index=False, encoding='utf-8-sig')
from google.colab import files
files.download('crc891.csv')