# -*- coding: utf-8 -*-
"""CrHoy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HHeDWNgHM-bzUYEqGlns3_o_rklCaOXX
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd
import re
import json
import time
from datetime import datetime

# -------------------------------------------------------------
# CONFIGURACIÓN
# -------------------------------------------------------------
BASE_URL = 'https://crhoy.com'

SECCIONES = {
    'nacionales':     'https://crhoy.com/nacionales/',
    'mundo':          'https://crhoy.com/mundo/',
    'economia':       'https://crhoy.com/economia/',
    'deportes':       'https://crhoy.com/deportes/',
    'entretenimiento':'https://crhoy.com/entretenimiento/',
    'tecnologia':     'https://crhoy.com/tecnologia/',
    'gusto':          'https://crhoy.com/gusto/',
}

HEADERS = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'}
DELAY = 1.5

MESES = {
    'ene':'01','feb':'02','mar':'03','abr':'04',
    'may':'05','jun':'06','jul':'07','ago':'08',
    'sep':'09','oct':'10','nov':'11','dic':'12'
}

# -------------------------------------------------------------
# FUNCIONES
# -------------------------------------------------------------
def get_soup(url, session):
    """Petición HTTP → BeautifulSoup. Retorna None si falla."""
    try:
        response = session.get(url, timeout=10)
        response.raise_for_status()
        return BeautifulSoup(response.text, 'html.parser')
    except requests.RequestException as e:
        print(f"  Error: {url} -> {e}")
        return None

def clean_text(text):
    """Elimina espacios y saltos de línea extra."""
    return re.sub(r'\s+', ' ', text).strip() if text else ""

def parse_date_crhoy(text):
    """
    Convierte "6 de Abr. 2026 | 1:35 am" → "2026-04-06"
    También maneja "2026-04-06T01:35:25" directo.
    """
    if not text:
        return "Sin fecha"
    text = text.strip()
    if re.match(r'\d{4}-\d{2}-\d{2}', text):
        return text[:10]
    m = re.search(r'(\d{1,2})\s+de\s+(\w+)\.?\s+(\d{4})', text, re.IGNORECASE)
    if m:
        dia  = m.group(1).zfill(2)
        mes  = MESES.get(m.group(2).lower()[:3], '01')
        anio = m.group(3)
        return f"{anio}-{mes}-{dia}"
    return "Sin fecha"

def extract_article_data(soup):
    """
    Extrae título, fecha, sección y contenido del artículo.
    Estructura HTML de crhoy.com (Next.js + Tailwind):
      - Meta JSON: <script id="__cr_post_meta"> {"author":...,"category":...}
      - Título:    <h1>
      - Fecha:     <span> con patrón "6 de Abr. 2026 | 1:35 am"
      - Sección:   del JSON o etiqueta naranja
      - Contenido: <div class="...wp-article..."> → <p>
    """
    # --- Sección desde JSON embebido ---
    section = "sin-seccion"
    meta_tag = soup.find('script', id='__cr_post_meta')
    if meta_tag:
        try:
            meta = json.loads(meta_tag.string)
            raw_sec = meta.get('category', '')
            if raw_sec:
                section = raw_sec.lower()
                section = section.replace('á','a').replace('é','e').replace('í','i').replace('ó','o').replace('ú','u')
                section = re.sub(r'\s+', '-', section).strip('-')
        except Exception:
            pass

    # Fallback: etiqueta naranja sobre el título
    if section == "sin-seccion":
        tag = soup.find('span', class_=re.compile(r'orange-label|bg-orange'))
        if tag:
            section = clean_text(tag.get_text()).lower()
            section = section.replace('á','a').replace('é','e').replace('í','i').replace('ó','o').replace('ú','u')
            section = re.sub(r'\s+', '-', section).strip('-')

    # --- Título ---
    title_tag = soup.find('h1')
    title = clean_text(title_tag.get_text()) if title_tag else "Sin titulo"

    # --- Fecha ---
    date = "Sin fecha"
    for span in soup.find_all('span'):
        txt = clean_text(span.get_text())
        if re.search(r'\d{1,2}\s+de\s+\w+', txt, re.IGNORECASE):
            date = parse_date_crhoy(txt)
            if date != "Sin fecha":
                break
    # Fallback desde JSON
    if date == "Sin fecha" and meta_tag:
        try:
            meta = json.loads(meta_tag.string)
            raw_date = meta.get('date', '')
            if raw_date:
                date = raw_date[:10]
        except Exception:
            pass

    # --- Contenido ---
    content = "Contenido no encontrado"
    content_div = soup.find('div', class_=re.compile(r'wp-article'))
    if not content_div:
        content_div = soup.find('article')
    if content_div:
        for tag in content_div.find_all(['script', 'style', 'iframe', 'aside', 'figure', 'noscript']):
            tag.decompose()
        parrafos = content_div.find_all('p')
        if parrafos:
            content = " ".join(clean_text(p.get_text()) for p in parrafos if p.get_text(strip=True))
        else:
            content = clean_text(content_div.get_text())

    return title, date, section, content

# -------------------------------------------------------------
# SCRAPING PRINCIPAL
# -------------------------------------------------------------
data = []
urls_vistas = set()

EXCLUIR = ['/busqueda', '/pro', '/autor', '/categoria',
           '/gusto/guias', '/gusto/recomendaciones',
           '/programa', '/membresia', '/nosotros',
           '/contacto', '/enterese', '/caricatura', '#']

with requests.Session() as session:
    session.headers.update(HEADERS)

    for section, url_seccion in SECCIONES.items():
        print(f"\nSeccion: {section.upper()} -> {url_seccion}")

        main_soup = get_soup(url_seccion, session)
        if main_soup is None:
            print(f"  No se pudo acceder.")
            continue

        links = []
        for a in main_soup.find_all('a', href=True):
            href = a['href']
            if (href.startswith('/') and
                len(href) > 10 and
                not any(x in href for x in EXCLUIR)):
                full = BASE_URL + href
                if full not in urls_vistas:
                    if a.find(['h2', 'h3']) or a.find(class_=re.compile(r'text-body')):
                        links.append(full)
                        urls_vistas.add(full)

        print(f"  {len(links)} articulos nuevos encontrados.")

        for i, link in enumerate(links, 1):
            print(f"    [{i}/{len(links)}] {link.split('/')[-2][:55]}...")
            time.sleep(DELAY)

            article_soup = get_soup(link, session)
            if article_soup:
                title, date, section_real, content = extract_article_data(article_soup)
            else:
                title, date, section_real, content = "Error", "Error", section, "Error al recuperar"

            data.append({
                'source':           'crhoy',
                'url':              link,
                'title':            title,
                'publication_date': date,
                'scraping_date':    datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
                'section':          section_real,
                'full_text':        content,
                'language':         'es'
            })

# -------------------------------------------------------------
# RESULTADO FINAL — Schema v1.0
# -------------------------------------------------------------
try:
    from google.colab import files
except ImportError:
    files = None

df = pd.DataFrame(data, columns=[
    'source', 'url', 'title', 'publication_date',
    'scraping_date', 'section', 'full_text', 'language'
])

# Validaciones estándar v1.0
df = df.drop_duplicates(subset='url')
df = df[df['full_text'].str.len() >= 300]
df = df[~df['publication_date'].isin(['Sin fecha', 'Error'])]

today_str = datetime.now().strftime('%Y%m%d')
output_file = f'crhoy_{today_str}.csv'

df.to_csv(output_file, index=False, encoding='utf-8', sep=',', na_rep='NULL')
files.download(output_file)

print(f"\nDataFrame: {len(df)} filas x {len(df.columns)} columnas")
print(f"Archivo guardado: {output_file}")
df.head(8)

from google.colab import files

today_str = datetime.now().strftime('%Y%m%d')
output_file = f'crhoy_{today_str}.csv'

df.to_csv(output_file, index=False, encoding='utf-8', sep=',', na_rep='NULL')
files.download(output_file)