# -*- coding: utf-8 -*-
"""Digital506.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1goUP8ijBXWqluoEB82e46FhLCE2L7CEl
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd
import re
import time
from datetime import datetime

# -------------------------------------------------------------
# CONFIGURACIÓN
# -------------------------------------------------------------
SECCIONES = {
    'nacionales':      'https://digital506.com/category/nacionales/',
    'politica':        'https://digital506.com/category/politica/',
    'internacionales': 'https://digital506.com/category/internacionales/',
    'opinion':         'https://digital506.com/category/opinion/',
    'economia':        'https://digital506.com/category/economia/',
    'deportes':        'https://digital506.com/category/deportes/',
    'cultura':         'https://digital506.com/category/cultura/',
    'salud':           'https://digital506.com/category/salud/',
    'tecnologia':      'https://digital506.com/category/tecnologia/',
    'ambiente':        'https://digital506.com/category/ambiente/',
    'turismo':         'https://digital506.com/category/turismo/',
    'educacion':       'https://digital506.com/category/educacion/',
    'sucesos':         'https://digital506.com/category/sucesos/',
    'pymes':           'https://digital506.com/category/pymes/',
    'entretenimiento': 'https://digital506.com/category/entretenimiento/',
}

HEADERS = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'}
DELAY = 1.5

# -------------------------------------------------------------
# FUNCIONES
# -------------------------------------------------------------
def get_soup(url, session):
    try:
        response = session.get(url, timeout=10)
        response.raise_for_status()
        return BeautifulSoup(response.text, 'html.parser')
    except requests.RequestException as e:
        print(f"  Error: {url} -> {e}")
        return None

def clean_text(text):
    return re.sub(r'\s+', ' ', text).strip() if text else ""

def es_url_articulo(href):
    if not href or 'digital506.com' not in href:
        return False
    excluir = ['/category/', '/author/', '/page/', '/tag/', '/privacy',
               '/wp-content/', '#', 'mailto:', 'javascript:']
    for ex in excluir:
        if ex in href:
            return False
    if href.rstrip('/') == 'https://digital506.com':
        return False
    slug = href.replace('https://digital506.com/', '').strip('/')
    if not slug or len(slug) < 5:
        return False
    return True

def extract_article_data(soup):
    # Título — confirmado: h1.tdb-title-text
    title_tag = soup.find('h1', class_='tdb-title-text')
    title = clean_text(title_tag.get_text()) if title_tag else None

    # Fecha — clase real confirmada: entry-date updated td-module-date
    # Hay varios <time> en la página (sidebar, relacionados), tomamos el primero
    # que esté DENTRO del artículo principal (tdi_59 o td-main-content-wrap)
    publication_date = None
    main_wrap = soup.find('div', class_=lambda c: c and 'td-main-content-wrap' in c)
    if not main_wrap:
        main_wrap = soup  # fallback al soup completo
    time_tag = main_wrap.find('time', class_=lambda c: c and 'entry-date' in c)
    if time_tag and time_tag.get('datetime'):
        publication_date = time_tag['datetime'][:10]  # "2026-04-06"

    # Sección — primer a[href*="/category/"] de un solo nivel
    section = None
    for a in soup.select('a[href*="/category/"]'):
        href = a.get('href', '')
        partes = [p for p in href.split('/') if p and p != 'category']
        if len(partes) == 1:
            section = clean_text(a.get_text()).lower()
            section = (section.replace('á','a').replace('é','e')
                               .replace('í','i').replace('ó','o')
                               .replace('ú','u').replace(' ','-'))
            break

    # Contenido — selector corregido: div.td-post-content (dentro de tdb_single_content)
    full_text = None
    content_div = soup.find('div', class_=lambda c: c and 'td-post-content' in c)
    if content_div:
        for tag in content_div.find_all(['script', 'style', 'iframe', 'aside', 'nav', 'figure']):
            tag.decompose()
        full_text = clean_text(content_div.get_text())

    return title, publication_date, section, full_text

# -------------------------------------------------------------
# SCRAPING PRINCIPAL
# -------------------------------------------------------------
data = []
log_descartados = []
urls_vistas = set()

with requests.Session() as session:
    session.headers.update(HEADERS)

    for section, url in SECCIONES.items():
        print(f"\nSeccion: {section.upper()} -> {url}")
        main_soup = get_soup(url, session)
        if main_soup is None:
            print(f"  No se pudo acceder.")
            continue

        links = []
        for a in main_soup.find_all('a', href=True):
            href = a['href'].strip()
            if es_url_articulo(href) and href not in urls_vistas:
                links.append(href)
                urls_vistas.add(href)

        print(f"  {len(links)} articulos nuevos encontrados.")

        for i, link in enumerate(links, 1):
            print(f"    [{i}/{len(links)}] {link[:70]}...")
            time.sleep(DELAY)

            article_soup = get_soup(link, session)
            if article_soup:
                title, publication_date, section_real, full_text = extract_article_data(article_soup)
            else:
                title, publication_date, section_real, full_text = None, None, section, None

            scraping_date = datetime.now().strftime('%Y-%m-%d %H:%M:%S')

            if publication_date is None:
                log_descartados.append({'url': link, 'motivo': 'publication_date nulo'})
                continue
            if full_text is None or len(full_text) < 300:
                log_descartados.append({'url': link, 'motivo': f'full_text < 300 chars ({len(full_text) if full_text else 0})'})
                continue

            data.append({
                'source':           'digital506',
                'url':              link,
                'title':            title,
                'publication_date': publication_date,
                'scraping_date':    scraping_date,
                'section':          section_real,
                'full_text':        full_text,
                'language':         'es'
            })

# -------------------------------------------------------------
# RESULTADO FINAL
# -------------------------------------------------------------
df = pd.DataFrame(data)
print(f"\nDataFrame: {len(df)} filas x {len(df.columns)} columnas")
print(f"Descartados: {len(log_descartados)}")
df.head(8)

try:
    from google.colab import files
except ImportError:
    files = None
df.to_csv('DIGITAL506.csv', index=False, encoding='utf-8', sep=',', na_rep='NULL')
files.download('DIGITAL506.csv')