# -*- coding: utf-8 -*-
"""EL FINANCIERO.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/182vbjXDyM5sfwAr5TOPaamWd9NQUglEH
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd
import re
import time
from datetime import datetime

BASE_URL = 'https://www.elfinancierocr.com/'
HEADERS = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 '
                  '(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
}
DELAY = 1.5

def get_soup(url, session):
    try:
        response = session.get(url, timeout=10)
        response.raise_for_status()
        return BeautifulSoup(response.text, 'html.parser')
    except requests.RequestException as e:
        print(f"  ⚠️  Error: {url} → {e}")
        return None

def clean_text(text):
    return re.sub(r'\s+', ' ', text).strip() if text else ""

def extract_article_data(soup):
    title_tag = soup.find('h1', class_='b-headline')
    title = clean_text(title_tag.get_text()) if title_tag else "Sin título"

    date = "Sin fecha"
    time_tag = soup.find('time', class_='c-date')
    if time_tag:
        dt = time_tag.get('datetime', '')
        date = dt[:10] if dt else clean_text(time_tag.get_text())

    section_tag = soup.find('a', class_='c-overline')
    section = clean_text(section_tag.get_text()).lower() if section_tag else "sin-seccion"
    section = section.replace('á','a').replace('é','e').replace('í','i').replace('ó','o').replace('ú','u').replace(' ','-')

    content = "Contenido no encontrado"
    article_body = soup.find('article', class_=re.compile(r'article-body-wrapper'))
    if article_body:
        for tag in article_body.find_all(['script', 'style', 'iframe', 'figure', 'aside']):
            tag.decompose()
        content = clean_text(article_body.get_text())

    return title, date, section, content

data = []

with requests.Session() as session:
    session.headers.update(HEADERS)

    print(f"📰 Leyendo página principal: {BASE_URL}\n")
    main_soup = get_soup(BASE_URL, session)

    if main_soup is None:
        print("❌ No se pudo acceder a la página principal.")
    else:
        links = []
        for a in main_soup.find_all('a', href=True):
            href = a['href']
            if '/story/' in href and href not in links:
                if not href.startswith('http'):
                    href = 'https://www.elfinancierocr.com' + href
                links.append(href)

        print(f"✅ {len(links)} artículos encontrados.\n")

        for i, link in enumerate(links, 1):
            print(f"  [{i}/{len(links)}] {link.split('/')[-3][:60]}...")
            time.sleep(DELAY)

            article_soup = get_soup(link, session)
            if article_soup:
                title, date, section, content = extract_article_data(article_soup)
            else:
                title, date, section, content = "Error", "Error", "Error", "Error al recuperar"

            data.append({
                'source':           'elfinancierocr',
                'url':              link,
                'title':            title,
                'publication_date': date,
                'scraping_date':    datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
                'section':          section,
                'full_text':        content,
                'language':         'es'
            })

df3 = pd.DataFrame(data)
print(f"\n📊 DataFrame: {len(df3)} filas × {len(df3.columns)} columnas")
df3.head(8)

df3.to_csv('elfinancierocr.csv', index=False, encoding='utf-8', sep=',', na_rep='NULL')