# -*- coding: utf-8 -*-
"""El Jilguero.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YckWXYv1GR0mLGBbsXrGOHbkZn1Di2eu
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd
import re
import time
from datetime import datetime

# -------------------------------------------------------------
# CONFIGURACIÓN
# -------------------------------------------------------------
SECCIONES = {
    'alajuela':    'https://jilgueromedia.com/category/alajuela/',
    'belen':       'https://jilgueromedia.com/category/belen/',
    'poas':        'https://jilgueromedia.com/category/poas/',
    'nacional':    'https://jilgueromedia.com/category/nacional/',
    'salud':       'https://jilgueromedia.com/category/salud/',
    'ultima-hora': 'https://jilgueromedia.com/category/ultima-hora/',
    'opinion':     'https://jilgueromedia.com/category/opinion/',
}

HEADERS = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'}
DELAY = 1.5

# -------------------------------------------------------------
# FUNCIONES
# -------------------------------------------------------------
def get_soup(url, session):
    """Petición HTTP → BeautifulSoup. Retorna None si falla."""
    try:
        response = session.get(url, timeout=10)
        response.raise_for_status()
        return BeautifulSoup(response.text, 'html.parser')
    except requests.RequestException as e:
        print(f"  Error: {url} -> {e}")
        return None

def clean_text(text):
    """Elimina espacios y saltos de línea extra."""
    return re.sub(r'\s+', ' ', text).strip() if text else ""

def extract_article_data(soup):
    """
    Extrae título, fecha, sección y contenido del artículo.
    Estructura HTML de jilgueromedia.com:
      - Título:    <h1 class="title">
      - Fecha:     <span class="mg-blog-date"> → "MAR 14, 2025"
      - Sección:   <div class="mg-blog-category"><a> → "+ Belén"
      - Contenido: <article class="small single">
    """
    # Título
    title_tag = soup.find('h1', class_='title')
    title = clean_text(title_tag.get_text()) if title_tag else "Sin titulo"

    # Fecha — "MAR 14, 2025" → YYYY-MM-DD
    date = "Sin fecha"
    date_span = soup.find('span', class_='mg-blog-date')
    if date_span:
        date_raw = clean_text(date_span.get_text())
        try:
            date = datetime.strptime(date_raw, "%b %d, %Y").strftime("%Y-%m-%d")
        except:
            date = date_raw

    # Sección — limpiar "+ " del inicio y normalizar
    section = "sin-seccion"
    category_div = soup.find('div', class_='mg-blog-category')
    if category_div:
        a_tag = category_div.find('a')
        if a_tag:
            section = clean_text(a_tag.get_text()).lower()
            section = section.lstrip('+ ').strip()
            section = section.replace('á','a').replace('é','e').replace('í','i').replace('ó','o').replace('ú','u').replace(' ','-')

    # Contenido
    content = "Contenido no encontrado"
    article_body = soup.find('article', class_=re.compile(r'small single'))
    if article_body:
        for tag in article_body.find_all(['script', 'style', 'iframe', 'figure', 'aside']):
            tag.decompose()
        content = clean_text(article_body.get_text())

    return title, date, section, content

# -------------------------------------------------------------
# SCRAPING PRINCIPAL
# -------------------------------------------------------------
data = []

with requests.Session() as session:
    session.headers.update(HEADERS)

    for section, url in SECCIONES.items():
        print(f"\nSeccion: {section.upper()} -> {url}")
        main_soup = get_soup(url, session)
        if main_soup is None:
            print(f"  No se pudo acceder.")
            continue

        # Buscar solo en el contenido principal, excluyendo sidebar
        main_content = main_soup.find('div', id='content')
        if not main_content:
            main_content = main_soup

        links = []
        for h4 in main_content.find_all('h4'):
            a = h4.find('a', href=True)
            if a and 'jilgueromedia.com' in a['href'] and a['href'] not in links:
                links.append(a['href'])

        print(f"  {len(links)} articulos encontrados.")

        for i, link in enumerate(links, 1):
            print(f"    [{i}/{len(links)}] {link.split('/')[-2][:55]}...")
            time.sleep(DELAY)

            article_soup = get_soup(link, session)
            if article_soup:
                title, date, section_real, content = extract_article_data(article_soup)
            else:
                title, date, section_real, content = "Error", "Error", section, "Error al recuperar"

            data.append({
                'source':           'jilgueromedia',
                'url':              link,
                'title':            title,
                'publication_date': date,
                'scraping_date':    datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
                'section':          section_real,
                'full_text':        content,
                'language':         'es'
            })

# -------------------------------------------------------------
# RESULTADO FINAL — sin duplicados por URL
# -------------------------------------------------------------
df5 = pd.DataFrame(data).drop_duplicates(subset='url')
print(f"\nDataFrame: {len(df5)} filas x {len(df5.columns)} columnas")
df5.head(8)

from google.colab import files
df5.to_csv('jilgueromedia.csv', index=False, encoding='utf-8', sep=',', na_rep='NULL')
files.download('jilgueromedia.csv')