# -*- coding: utf-8 -*-
"""El Jornal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dS8Rit6Zf1gchEhpuHy-cy35f8578h3T
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd
import re
import time
from datetime import datetime

# -------------------------------------------------------------
# CONFIGURACIÓN
# -------------------------------------------------------------
SECCIONES = {
    'portada':           'https://eljornalcr.com/',
    'realidad-local':    'https://eljornalcr.com/category/realidad-local/',
    'realidad-nacional': 'https://eljornalcr.com/category/realidad-nacional2/',
    'realidad-global':   'https://eljornalcr.com/category/realidad-global/',
    'deportes':          'https://eljornalcr.com/category/deportes/',
    'bienes-raices':     'https://eljornalcr.com/category/bienes-raices/',
    'jornal-literario':  'https://eljornalcr.com/category/el-jornal-literario/',
    'cultura':           'https://eljornalcr.com/category/cultura/',
    'opinion':           'https://eljornalcr.com/category/opinion/',
    'emprendimiento':    'https://eljornalcr.com/category/emprendedurismo/',
}

HEADERS = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'}
DELAY = 1.5

# -------------------------------------------------------------
# FUNCIONES
# -------------------------------------------------------------
def get_soup(url, session):
    try:
        response = session.get(url, timeout=10)
        response.raise_for_status()
        return BeautifulSoup(response.text, 'html.parser')
    except requests.RequestException as e:
        print(f"  Error: {url} -> {e}")
        return None

def clean_text(text):
    return re.sub(r'\s+', ' ', text).strip() if text else ""

def extract_article_data(soup):
    # Título
    h1 = soup.find('h1')
    title = clean_text(h1.get_text()) if h1 else None

    # Fecha — "31 de octubre de 2025" → "2025-10-31"
    publication_date = None
    MESES = {'enero':'01','febrero':'02','marzo':'03','abril':'04','mayo':'05',
              'junio':'06','julio':'07','agosto':'08','septiembre':'09',
              'octubre':'10','noviembre':'11','diciembre':'12'}
    fecha_match = re.search(r'(\d{1,2})\s+de\s+(\w+)\s+de\s+(\d{4})', soup.get_text(' '))
    if fecha_match:
        dia, mes, anio = fecha_match.groups()
        mes_num = MESES.get(mes.lower())
        if mes_num:
            publication_date = f"{anio}-{mes_num}-{dia.zfill(2)}"

    # Sección
    section = None
    for a in soup.select('a'):
        if '/category/' in a.get('href', ''):
            section = clean_text(a.get_text()).lower()
            section = (section.replace('á','a').replace('é','e')
                               .replace('í','i').replace('ó','o')
                               .replace('ú','u').replace(' ','-'))
            break

    # Contenido
    full_text = None
    content_div = soup.select_one('.entry-content, .post-content, article')
    if content_div:
        for tag in content_div.find_all(['script', 'style', 'iframe', 'aside']):
            tag.decompose()
        full_text = clean_text(content_div.get_text())

    return title, publication_date, section, full_text

# -------------------------------------------------------------
# SCRAPING PRINCIPAL
# -------------------------------------------------------------
data = []
log_descartados = []
urls_vistas = set()

with requests.Session() as session:
    session.headers.update(HEADERS)

    for section, url in SECCIONES.items():
        print(f"\nSeccion: {section.upper()} -> {url}")
        main_soup = get_soup(url, session)
        if main_soup is None:
            print(f"  No se pudo acceder.")
            continue

        links = []
        for h3 in main_soup.find_all('h3'):
            a = h3.find('a', href=True)
            if a and 'eljornalcr.com' in a['href'] and a['href'] not in urls_vistas:
                links.append(a['href'])
                urls_vistas.add(a['href'])

        print(f"  {len(links)} articulos nuevos encontrados.")

        for i, link in enumerate(links, 1):
            print(f"    [{i}/{len(links)}] {link.split('/')[-2][:55]}...")
            time.sleep(DELAY)

            article_soup = get_soup(link, session)
            if article_soup:
                title, publication_date, section_real, full_text = extract_article_data(article_soup)
            else:
                title, publication_date, section_real, full_text = None, None, section, None

            scraping_date = datetime.now().strftime('%Y-%m-%d %H:%M:%S')

            # Validaciones obligatorias
            if publication_date is None:
                log_descartados.append({'url': link, 'motivo': 'publication_date nulo'})
                continue
            if full_text is None or len(full_text) < 300:
                log_descartados.append({'url': link, 'motivo': f'full_text < 300 chars ({len(full_text) if full_text else 0})'})
                continue

            data.append({
                'source':           'eljornalcr',
                'url':              link,
                'title':            title,
                'publication_date': publication_date,
                'scraping_date':    scraping_date,
                'section':          section_real,
                'full_text':        full_text,
                'language':         'es'
            })

# -------------------------------------------------------------
# RESULTADO FINAL
# -------------------------------------------------------------
df = pd.DataFrame(data)
print(f"\nDataFrame: {len(df)} filas x {len(df.columns)} columnas")
print(f"Descartados: {len(log_descartados)}")
df.head(8)

try:
    from google.colab import files
except ImportError:
    files = None
df.to_csv('eljornalcr.csv', index=False, encoding='utf-8', sep=',', na_rep='NULL')
files.download('eljornalcr.csv')