# -*- coding: utf-8 -*-
"""El mundo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vCtytXms_iSOCWsawg_oFb1vMbpq7nk5
"""

import requests
from bs4 import BeautifulSoup
import json
import csv
import time
from datetime import datetime

URL_BASE = "https://www.elmundo.es/"

HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/123.0.0.0 Safari/537.36"
    )
}

# Pausa entre requests para no sobrecargar el servidor (segundos)
DELAY = 1.5


def get_soup(url: str) -> BeautifulSoup:
    """Realiza el request y retorna un objeto BeautifulSoup."""
    response = requests.get(url, headers=HEADERS, timeout=15)
    response.raise_for_status()
    return BeautifulSoup(response.text, "html.parser")


def scrape_lista_noticias(url: str) -> list[dict]:
    """
    Extrae título, enlace y fecha de cada noticia en el listado.
    El Mundo (elmundo.es) estructura típica:
      - Artículos dentro de <article> o <li> con clase 'ue-c-cover-content'
      - Título en <h2> o <h3> con clase 'ue-c-cover-content__headline'
      - Fecha en <time> con clase 'ue-c-cover-content__date' o atributo datetime
      - Sección visible en el breadcrumb o en la URL del artículo
    """
    soup = get_soup(url)

    # Selector principal: artículos de portada/listado de elmundo.es
    contenedores = soup.select(
        "article.ue-c-cover-content, "
        "li.ue-c-cover-content, "
        "article[class*='cover-content']"
    )

    # Fallback genérico
    if not contenedores:
        contenedores = soup.select("article")

    noticias = []
    for item in contenedores:
        # Título y enlace — varias clases posibles según la sección
        titulo_tag = item.select_one(
            "h2.ue-c-cover-content__headline a, "
            "h3.ue-c-cover-content__headline a, "
            "h2[class*='headline'] a, "
            "h3[class*='headline'] a"
        )

        # Fallback: primer enlace que contenga texto de título
        if not titulo_tag:
            titulo_tag = item.select_one("a[href]")

        titulo = titulo_tag.get_text(strip=True) if titulo_tag else "Sin título"
        enlace = titulo_tag["href"] if titulo_tag and titulo_tag.has_attr("href") else ""

        # Asegurar URL absoluta
        if enlace and enlace.startswith("/"):
            enlace = "https://www.elmundo.es" + enlace

        # Fecha
        fecha_tag = item.select_one(
            "time.ue-c-cover-content__date, "
            "time[class*='date'], "
            "time[datetime]"
        )
        if fecha_tag:
            fecha = fecha_tag.get("datetime", "") or fecha_tag.get_text(strip=True)
        else:
            fecha = "Sin fecha"

        # Sección: leer de la clase CSS del contenedor o de la URL
        seccion = _extraer_seccion(item, enlace)

        noticias.append({
            "source": "elmundo",
            "url": enlace,
            "title": titulo,
            "publication_date": fecha,
            "scraping_date": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            "section": seccion,
            "full_text": "",
            "language": "es"
        })

    # Eliminar duplicados por URL
    vistos = set()
    noticias_unicas = []
    for n in noticias:
        if n["url"] not in vistos and n["url"]:
            vistos.add(n["url"])
            noticias_unicas.append(n)

    return noticias_unicas


def _extraer_seccion(item: BeautifulSoup, enlace: str) -> str:
    """
    Intenta extraer la sección de la noticia desde:
    1. Etiqueta de categoría dentro del artículo
    2. Primer segmento de la URL (e.g. /espana/, /economia/)
    """
    # 1. Etiqueta visible de sección dentro del artículo
    seccion_tag = item.select_one(
        "span.ue-c-cover-content__section, "
        "a[class*='section'], "
        "span[class*='section']"
    )
    if seccion_tag:
        return seccion_tag.get_text(strip=True).title()

    # 2. Primer segmento de la URL
    if enlace:
        partes = [p for p in enlace.replace("https://www.elmundo.es", "").split("/") if p]
        if partes:
            return partes[0].replace("-", " ").title()

    return "Sin sección"


def scrape_texto_articulo(url: str) -> str:
    """
    Ingresa al artículo y extrae el texto del contenido principal.
    El Mundo usa:
      - div.ue-l-article__body  →  cuerpo principal del artículo
      - Párrafos dentro de <p> con clase 'ue-c-article__paragraph'
    """
    if not url:
        return ""

    soup = get_soup(url)

    # Selector principal
    contenedor = soup.select_one(
        "div.ue-l-article__body, "
        "div[class*='article__body'], "
        "div[class*='article-body']"
    )

    # Fallback
    if not contenedor:
        contenedor = soup.select_one(
            "div[class*='article__content'], "
            "div[class*='cuerpo-noticia'], "
            "section[class*='article']"
        )

    if not contenedor:
        return "No se pudo extraer el contenido."

    partes = []
    for tag in contenedor.find_all(["p", "h2", "h3", "h4", "blockquote"]):
        # Ignorar párrafos de publicidad o de suscripción
        clases = " ".join(tag.get("class", []))
        if any(x in clases for x in ["ad", "paywall", "suscri", "related"]):
            continue
        texto = tag.get_text(strip=True)
        if texto:
            partes.append(texto)

    return "\n\n".join(partes)


def scraper_completo(url: str) -> list[dict]:
    """Orquesta el scraping: listado + texto de cada artículo."""
    print(f"🔍 Obteniendo listado de noticias: {url}\n")
    noticias = scrape_lista_noticias(url)
    print(f"📰 {len(noticias)} noticias encontradas. Extrayendo contenido...\n")

    for i, noticia in enumerate(noticias, 1):
        print(f"  [{i}/{len(noticias)}] {noticia['title'][:70]}...")
        try:
            noticia["full_text"] = scrape_texto_articulo(noticia["url"])
        except Exception as e:
            noticia["full_text"] = f"Error al extraer: {e}"
        time.sleep(DELAY)

    return noticias


def guardar_json(noticias: list[dict], archivo: str) -> None:
    with open(archivo, "w", encoding="utf-8") as f:
        json.dump(noticias, f, ensure_ascii=False, indent=2)
    print(f"\n✅ JSON guardado en: {archivo}")


def guardar_csv(noticias: list[dict], archivo: str) -> None:
    with open(archivo, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(
            f,
            fieldnames=[
                "source", "url", "title", "publication_date",
                "scraping_date", "section", "full_text", "language"
            ]
        )
        writer.writeheader()
        writer.writerows(noticias)
    print(f"✅ CSV guardado en: {archivo}")


def imprimir_resumen(noticias: list[dict]) -> None:
    print("\n" + "=" * 70)
    print("RESUMEN DE NOTICIAS EXTRAÍDAS — El Mundo")
    print("=" * 70)
    for i, n in enumerate(noticias, 1):
        print(f"\n{'─'*60}")
        print(f"[{i}] {n['title']}")
        print(f"    📅 {n['publication_date']}")
        print(f"    🏷  {n['section']}")
        print(f"    🔗 {n['url']}")
        preview = n["full_text"][:200].replace("\n", " ")
        print(f"    📄 {preview}{'...' if len(n['full_text']) > 200 else ''}")


if __name__ == "__main__":
    noticias = scraper_completo(URL_BASE)

    imprimir_resumen(noticias)

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    guardar_json(noticias, f"noticias_elmundo_{timestamp}.json")
    guardar_csv(noticias, f"noticias_elmundo_{timestamp}.csv")