# -*- coding: utf-8 -*-
"""el observador.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ITNWE5-swBvQT21d4cuVfWkZyaVtGscI
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd
import re
import time
from datetime import datetime

# -------------------------------------------------------------
# CONFIGURACIÓN
# -------------------------------------------------------------
SECCIONES = {
    'vision-pais':      'https://observador.cr/seccion/vision-pais/',
    'todo-politica':    'https://observador.cr/seccion/todo-politica/',
    'retina-economica': 'https://observador.cr/seccion/retina-economica/',
    'lente-mundial':    'https://observador.cr/seccion/lente-mundial/',
    'deportes':         'https://observador.cr/seccion/deportes/',
    'avenida':          'https://observador.cr/seccion/avenida/',
    'mascotas':         'https://observador.cr/seccion/mascotas/',
    'lente-comercial':  'https://observador.cr/seccion/lente-comercial/',
    'buenas-noticias':  'https://observador.cr/seccion/buenas-noticias/',
    'desde-la-columna': 'https://observador.cr/seccion/desde-la-columna/',
    'bbc':              'https://observador.cr/seccion/bbc/',
}

HEADERS = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'}
DELAY = 1.5

# -------------------------------------------------------------
# FUNCIONES
# -------------------------------------------------------------
def get_soup(url, session):
    """Petición HTTP → BeautifulSoup. Retorna None si falla."""
    try:
        response = session.get(url, timeout=10)
        response.raise_for_status()
        return BeautifulSoup(response.text, 'html.parser')
    except requests.RequestException as e:
        print(f"  Error: {url} -> {e}")
        return None

def clean_text(text):
    """Elimina espacios y saltos de línea extra."""
    return re.sub(r'\s+', ' ', text).strip() if text else ""

def extract_article_data(soup):
    """
    Extrae título, fecha, sección y contenido del artículo.
    Estructura HTML de observador.cr (WordPress custom):
      - Título:    <h1> dentro de <div class="meta">
      - Fecha:     <time datetime="YYYY-MM-DDTHH:MM:SS-06:00">
      - Sección:   <span> dentro de <div class="meta">
      - Contenido: <div class="entry-text"> → párrafos <p>
    """
    # Título
    title_tag = soup.find('h1')
    title = clean_text(title_tag.get_text()) if title_tag else "Sin titulo"

    # Fecha — datetime="2026-04-06T11:55:02-06:00" → YYYY-MM-DD
    date = "Sin fecha"
    time_tag = soup.find('time', datetime=True)
    if time_tag:
        try:
            date = time_tag['datetime'][:10]
        except:
            date = clean_text(time_tag.get_text())

    # Sección — <span>Todo Política</span> dentro de <div class="meta">
    section = "sin-seccion"
    meta_div = soup.find('div', class_='meta')
    if meta_div:
        span = meta_div.find('span')
        if span:
            section = clean_text(span.get_text()).lower()
            section = section.replace('á','a').replace('é','e').replace('í','i').replace('ó','o').replace('ú','u')
            section = re.sub(r'\s+', '-', section)
            section = re.sub(r'-+', '-', section).strip('-')

    # Contenido — <div class="entry-text"> → <p>
    content = "Contenido no encontrado"
    entry = soup.find('div', class_='entry-text')
    if entry:
        for tag in entry.find_all(['script', 'style', 'iframe', 'aside', 'figure', 'noscript']):
            tag.decompose()
        parrafos = entry.find_all('p')
        if parrafos:
            content = " ".join(clean_text(p.get_text()) for p in parrafos if p.get_text(strip=True))
        else:
            content = clean_text(entry.get_text())

    return title, date, section, content

# -------------------------------------------------------------
# SCRAPING PRINCIPAL
# -------------------------------------------------------------
data = []
urls_vistas = set()

with requests.Session() as session:
    session.headers.update(HEADERS)

    for section, url in SECCIONES.items():
        print(f"\nSeccion: {section.upper()} -> {url}")

        main_soup = get_soup(url, session)
        if main_soup is None:
            print(f"  No se pudo acceder.")
            continue

        # Links — solo del bloque principal <div class="list">
        # para no capturar links del sidebar
        links = []
        list_div = main_soup.find('div', class_='list')
        if list_div:
            for promo in list_div.find_all('div', class_='promo'):
                a = promo.find('h3', class_='title')
                if a:
                    a = a.find('a', href=True)
                    if a and 'observador.cr' in a['href'] and a['href'] not in urls_vistas:
                        links.append(a['href'])
                        urls_vistas.add(a['href'])

        print(f"  {len(links)} articulos nuevos encontrados.")

        for i, link in enumerate(links, 1):
            print(f"    [{i}/{len(links)}] {link.split('/')[-2][:55]}...")
            time.sleep(DELAY)

            article_soup = get_soup(link, session)
            if article_soup:
                title, date, section_real, content = extract_article_data(article_soup)
            else:
                title, date, section_real, content = "Error", "Error", section, "Error al recuperar"

            data.append({
                'source':           'observadorcr',
                'url':              link,
                'title':            title,
                'publication_date': date,
                'scraping_date':    datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
                'section':          section_real,
                'full_text':        content,
                'language':         'es'
            })

# -------------------------------------------------------------
# RESULTADO FINAL
# -------------------------------------------------------------
df = pd.DataFrame(data)
print(f"\nDataFrame: {len(df)} filas x {len(df.columns)} columnas")
df.head(8)

try:
    from google.colab import files
except ImportError:
    files = None

today_str = datetime.now().strftime('%Y%m%d')
output_file = f'observadorcr_{today_str}.csv'

df.to_csv(output_file, index=False, encoding='utf-8', sep=',', na_rep='NULL')
files.download(output_file)