# -*- coding: utf-8 -*-
"""El Sol de Occidente.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NElJ4Dg7sC4emgDFgr2F-BzrOJ2zWQSi

# NOTA: Secciones de cantones no extraídas
# Las siguientes secciones de elsoldeoccidente.com cargan su contenido
# dinámicamente con JavaScript, por lo que BeautifulSoup no puede acceder a ellas:
# - San Ramón
# - Palmares
# - Naranjo
# - Sarchí
# - Atenas
# - Grecia
# - Poás
# - Zarcero
# - Alajuela
# - San José
#
# Para extraer estas secciones se requiere Selenium u otra herramienta
# que ejecute JavaScript en un navegador real.
# El DataFrame df7 contiene únicamente las secciones accesibles:
# economia-y-finanzas, espectaculos, educacion, arte-y-cultura, turismo, salud.
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd
import re
import time
from datetime import datetime

# -------------------------------------------------------------
# CONFIGURACIÓN
# -------------------------------------------------------------
SECCIONES = {
    'san-ramon':           'https://elsoldeoccidente.com/cantonales/san-ramon-cantonales/',
    'palmares':            'https://elsoldeoccidente.com/cantonales/palmares/',
    'naranjo':             'https://elsoldeoccidente.com/cantonales/naranjo/',
    'sarchi':              'https://elsoldeoccidente.com/cantonales/sarchi/',
    'atenas':              'https://elsoldeoccidente.com/cantonales/atenas/',
    'grecia':              'https://elsoldeoccidente.com/cantonales/grecia/',
    'poas':                'https://elsoldeoccidente.com/cantonales/poas/',
    'zarcero':             'https://elsoldeoccidente.com/cantonales/zarcero/',
    'alajuela':            'https://elsoldeoccidente.com/cantonales/alajuela/',
    'san-jose':            'https://elsoldeoccidente.com/cantonales/san-jose/',
    'costa-rica':          'https://elsoldeoccidente.com/costa-rica/',
    'economia-y-finanzas': 'https://elsoldeoccidente.com/economia-y-finanzas/',
    'salud':               'https://elsoldeoccidente.com/salud/',
    'espectaculos':        'https://elsoldeoccidente.com/espectaculos/',
    'arte-y-cultura':      'https://elsoldeoccidente.com/arte-y-cultura/',
    'turismo':             'https://elsoldeoccidente.com/turismo/',
    'deportes':            'https://elsoldeoccidente.com/deportes/',
    'educacion':           'https://elsoldeoccidente.com/educacion/',
}

HEADERS = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'}
DELAY = 1.5

# -------------------------------------------------------------
# FUNCIONES
# -------------------------------------------------------------
def get_soup(url, session):
    """Petición HTTP → BeautifulSoup. Retorna None si falla."""
    try:
        response = session.get(url, timeout=10)
        response.raise_for_status()
        return BeautifulSoup(response.text, 'html.parser')
    except requests.RequestException as e:
        print(f"  Error: {url} -> {e}")
        return None

def clean_text(text):
    """Elimina espacios y saltos de línea extra."""
    return re.sub(r'\s+', ' ', text).strip() if text else ""

def extract_article_data(soup):
    """
    Extrae título, fecha, sección y contenido del artículo.
    Estructura HTML de elsoldeoccidente.com:
      - Título:    <h1 class="entry-title">
      - Fecha:     <span class="entry-meta-date updated"><a> → "22/03/2026"
      - Sección:   <span class="entry-meta-categories"><a>
      - Contenido: <div class="entry-content mh-clearfix">
    """
    # Título
    title_tag = soup.find('h1', class_='entry-title')
    title = clean_text(title_tag.get_text()) if title_tag else "Sin titulo"

    # Fecha — "22/03/2026" → "2026-03-22"
    date = "Sin fecha"
    date_span = soup.find('span', class_='entry-meta-date')
    if date_span:
        a_tag = date_span.find('a')
        date_raw = clean_text(a_tag.get_text()) if a_tag else clean_text(date_span.get_text())
        try:
            date = datetime.strptime(date_raw, "%d/%m/%Y").strftime("%Y-%m-%d")
        except:
            date = date_raw

    # Sección
    section = "sin-seccion"
    cat_span = soup.find('span', class_='entry-meta-categories')
    if cat_span:
        a_tag = cat_span.find('a')
        if a_tag:
            section = clean_text(a_tag.get_text()).lower()
            section = section.replace('á','a').replace('é','e').replace('í','i').replace('ó','o').replace('ú','u').replace(' ','-')

    # Contenido
    content = "Contenido no encontrado"
    content_div = soup.find('div', class_=re.compile(r'entry-content'))
    if content_div:
        for tag in content_div.find_all(['script', 'style', 'iframe', 'aside']):
            tag.decompose()
        content = clean_text(content_div.get_text())

    return title, date, section, content

# -------------------------------------------------------------
# SCRAPING PRINCIPAL
# -------------------------------------------------------------
data = []
urls_vistas = set()

with requests.Session() as session:
    session.headers.update(HEADERS)

    for section, url in SECCIONES.items():
        print(f"\nSeccion: {section.upper()} -> {url}")
        main_soup = get_soup(url, session)
        if main_soup is None:
            print(f"  No se pudo acceder.")
            continue

        # Links desde h3.entry-title.mh-loop-title
        links = []
        for h3 in main_soup.find_all('h3', class_=re.compile(r'entry-title')):
            a = h3.find('a', href=True)
            if a and 'elsoldeoccidente.com' in a['href'] and a['href'] not in urls_vistas:
                links.append(a['href'])
                urls_vistas.add(a['href'])

        print(f"  {len(links)} articulos nuevos encontrados.")

        for i, link in enumerate(links, 1):
            print(f"    [{i}/{len(links)}] {link.split('/')[-2][:55]}...")
            time.sleep(DELAY)

            article_soup = get_soup(link, session)
            if article_soup:
                title, date, section_real, content = extract_article_data(article_soup)
            else:
                title, date, section_real, content = "Error", "Error", section, "Error al recuperar"

            data.append({
                'source':           'elsoldeoccidente',
                'url':              link,
                'title':            title,
                'publication_date': date,
                'scraping_date':    datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
                'section':          section_real,
                'full_text':        content,
                'language':         'es'
            })

# -------------------------------------------------------------
# RESULTADO FINAL
# -------------------------------------------------------------
df7 = pd.DataFrame(data)
print(f"\nDataFrame: {len(df7)} filas x {len(df7.columns)} columnas")
df7.head(8)

print(df7['section'].value_counts())

from google.colab import files
df7.to_csv('elsoldeoccidente.csv', index=False, encoding='utf-8', sep=',', na_rep='NULL')
files.download('elsoldeoccidente.csv')