# -*- coding: utf-8 -*-
"""El seminario.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xk2BeV60tuwGkKonnjY9bJLXr1CNhY1a
"""

import requests
from bs4 import BeautifulSoup
import json
import csv
import time
from datetime import datetime

URL_BASE = "https://semanariouniversidad.com/"

HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/123.0.0.0 Safari/537.36"
    )
}

# Pausa entre requests para no sobrecargar el servidor (segundos)
DELAY = 1.5


def get_soup(url: str) -> BeautifulSoup:
    """Realiza el request y retorna un objeto BeautifulSoup."""
    response = requests.get(url, headers=HEADERS, timeout=15)
    response.raise_for_status()
    return BeautifulSoup(response.text, "html.parser")


# Selectores de título a probar en orden de prioridad
TITULO_SELECTORES = [
    # WordPress clásico
    "h2.entry-title a",
    "h3.entry-title a",
    "h1.entry-title a",
    # Clases genéricas con 'title'
    "h2.post-title a",
    "h3.post-title a",
    "[class*='entry-title'] a",
    "[class*='post-title'] a",
    # Tema Newspaper / td_module
    "h3.td-module-title a",
    "h4.td-module-title a",
    # Tema Jannah / jeg_post
    "h3.jeg_post_title a",
    "h4.jeg_post_title a",
    # Tema Soledad / mh-posts-list
    "h3.mh-posts-list-title a",
    # Fallback: cualquier enlace dentro de h2/h3/h4 del artículo
    "h2 a[href]",
    "h3 a[href]",
    "h4 a[href]",
]


def _extraer_titulo_y_enlace(item: BeautifulSoup) -> tuple[str, str]:
    """
    Prueba una lista de selectores en orden hasta encontrar título + enlace.
    Si ninguno funciona, intenta el primer <a> con texto razonablemente largo.
    """
    for selector in TITULO_SELECTORES:
        tag = item.select_one(selector)
        if tag:
            texto = tag.get_text(strip=True)
            href = tag.get("href", "")
            if texto and href:
                return texto, href

    # Último recurso: primer enlace con texto ≥ 20 caracteres
    for a in item.find_all("a", href=True):
        texto = a.get_text(strip=True)
        if len(texto) >= 20:
            return texto, a["href"]

    return "Sin título", ""


def scrape_lista_noticias(url: str) -> list[dict]:
    """
    Extrae título, enlace y fecha de cada noticia en el listado.
    Semanario Universidad (WordPress): prueba múltiples selectores
    para cubrir distintas versiones del tema.
    """
    soup = get_soup(url)

    # Selector principal: etiquetas <article> con clase que contenga 'post'
    contenedores = soup.select("article.post, article.type-post, article.category-ultimas")

    # Fallback 1: cualquier <article>
    if not contenedores:
        contenedores = soup.select("article")

    # Fallback 2: divs típicos de temas premium
    if not contenedores:
        contenedores = soup.select(
            "div.td_module_mx, div.td_module_flex, "
            "div.jeg_post, div[class*='post-item'], "
            "div[class*='news-item']"
        )

    # Diagnóstico si aún no hay contenedores
    if not contenedores:
        print("⚠️  No se encontraron contenedores de noticias.")
        print("    Revisá la estructura HTML con:")
        print("    print(soup.prettify()[:3000])")

    noticias = []
    for item in contenedores:
        titulo, enlace = _extraer_titulo_y_enlace(item)

        # Fecha: <time class="entry-date published" datetime="...">
        fecha_tag = item.select_one("time.entry-date, time.published, time[datetime]")
        if fecha_tag:
            # Preferir el atributo datetime (ISO 8601) sobre el texto visible
            fecha = fecha_tag.get("datetime", "") or fecha_tag.get_text(strip=True)
        else:
            fecha = "Sin fecha"

        # Sección: se intenta leer de la clase CSS del <article> (e.g. category-nacional)
        clases = item.get("class", [])
        seccion = "Sin sección"
        for cls in clases:
            if cls.startswith("category-"):
                seccion = cls.replace("category-", "").replace("-", " ").title()
                break

        noticias.append({
            "source": "semanariouniversidad",
            "url": enlace,
            "title": titulo,
            "publication_date": fecha,
            "scraping_date": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            "section": seccion,
            "full_text": "",
            "language": "es"
        })

    return noticias


def scrape_texto_articulo(url: str) -> str:
    """
    Ingresa al artículo y extrae el texto del contenido principal.
    Semanario Universidad (WordPress):
      div.entry-content  →  contenedor principal del artículo
    """
    if not url:
        return ""

    soup = get_soup(url)

    # Selector principal para WordPress
    contenedor = soup.select_one("div.entry-content")

    # Fallbacks adicionales
    if not contenedor:
        contenedor = soup.select_one("div.post-content, div.article-content, div.td-post-content")

    if not contenedor:
        contenedor = soup.select_one("[class*='entry-content'], [class*='post-content']")

    if not contenedor:
        return "No se pudo extraer el contenido."

    # Extraer párrafos y subtítulos; ignorar scripts/anuncios
    partes = []
    for tag in contenedor.find_all(["p", "h2", "h3", "h4", "blockquote"]):
        texto = tag.get_text(strip=True)
        if texto:
            partes.append(texto)

    return "\n\n".join(partes)


def scraper_completo(url: str) -> list[dict]:
    """Orquesta el scraping: listado + texto de cada artículo."""
    print(f"🔍 Obteniendo listado de noticias: {url}\n")
    noticias = scrape_lista_noticias(url)
    print(f"📰 {len(noticias)} noticias encontradas. Extrayendo contenido...\n")

    for i, noticia in enumerate(noticias, 1):
        print(f"  [{i}/{len(noticias)}] {noticia['title'][:70]}...")
        try:
            noticia["full_text"] = scrape_texto_articulo(noticia["url"])
        except Exception as e:
            noticia["full_text"] = f"Error al extraer: {e}"
        time.sleep(DELAY)

    return noticias


def guardar_json(noticias: list[dict], archivo: str) -> None:
    with open(archivo, "w", encoding="utf-8") as f:
        json.dump(noticias, f, ensure_ascii=False, indent=2)
    print(f"\n✅ JSON guardado en: {archivo}")


def guardar_csv(noticias: list[dict], archivo: str) -> None:
    with open(archivo, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(
            f,
            fieldnames=[
                "source", "url", "title", "publication_date",
                "scraping_date", "section", "full_text", "language"
            ]
        )
        writer.writeheader()
        writer.writerows(noticias)
    print(f"✅ CSV guardado en: {archivo}")


def imprimir_resumen(noticias: list[dict]) -> None:
    print("\n" + "=" * 70)
    print("RESUMEN DE NOTICIAS EXTRAÍDAS — Semanario Universidad")
    print("=" * 70)
    for i, n in enumerate(noticias, 1):
        print(f"\n{'─'*60}")
        print(f"[{i}] {n['title']}")
        print(f"    📅 {n['publication_date']}")
        print(f"    🏷  {n['section']}")
        print(f"    🔗 {n['url']}")
        preview = n["full_text"][:200].replace("\n", " ")
        print(f"    📄 {preview}{'...' if len(n['full_text']) > 200 else ''}")


if __name__ == "__main__":
    noticias = scraper_completo(URL_BASE)

    imprimir_resumen(noticias)

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    guardar_json(noticias, f"noticias_semanario_{timestamp}.json")
    guardar_csv(noticias, f"noticias_semanario_{timestamp}.csv")