# -*- coding: utf-8 -*-
"""elnortehoy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13tNX_lxe4UVYRYl1wG6-iPZY6uuAjbSX
"""

# Ver filas sin título
sin_titulo = df6[df6['title'] == 'Sin titulo']
print(f"Sin título: {len(sin_titulo)}")

# Ver filas sin contenido
sin_contenido = df6[df6['full_text'].str.strip() == '']
print(f"Sin contenido: {len(sin_contenido)}")

# Ver filas sin fecha
sin_fecha = df6[df6['publication_date'] == 'Sin fecha']
print(f"Sin fecha: {len(sin_fecha)}")

# Resumen general
print(f"\nTotal filas: {len(df6)}")
print(df6[['title', 'publication_date', 'section', 'full_text']].head(10))

import requests
from bs4 import BeautifulSoup
import pandas as pd
import re
import time
from datetime import datetime

# -------------------------------------------------------------
# CONFIGURACIÓN
# -------------------------------------------------------------
SECCIONES = {
    'tecnologia':     'https://elnortehoycr.com/category/tecnologia/',
    'historia':       'https://elnortehoycr.com/category/historia/',
    'ambiente':       'https://elnortehoycr.com/category/ambiente/',
    'agricultura':    'https://elnortehoycr.com/category/agricultura/',
    'cultura':        'https://elnortehoycr.com/category/cultura/',
    'turismo':        'https://elnortehoycr.com/category/turismo/',
    'educacion':      'https://elnortehoycr.com/category/educacion/',
    'infraestructura':'https://elnortehoycr.com/category/infraestructura/',
    'politica':       'https://elnortehoycr.com/category/politica/',
    'deportes':       'https://elnortehoycr.com/category/deportes/',
    'economia':       'https://elnortehoycr.com/category/economia/',
    'opinion':        'https://elnortehoycr.com/category/opinion/',
    'guatuso':        'https://elnortehoycr.com/category/guatuso/',
    'rio-cuarto':     'https://elnortehoycr.com/category/rio-cuarto/',
    'sarapiqui':      'https://elnortehoycr.com/category/sarapiqui/',
    'san-carlos':     'https://elnortehoycr.com/category/san-carlos/',
    'upala':          'https://elnortehoycr.com/category/upala/',
    'los-chiles':     'https://elnortehoycr.com/category/los-chiles/',
    'nacionales':     'https://elnortehoycr.com/category/nacionales/',
    'reportajes':     'https://elnortehoycr.com/category/reportajes/',
}

HEADERS = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'}
DELAY = 1.5

MESES = {
    'enero':'01','febrero':'02','marzo':'03','abril':'04',
    'mayo':'05','junio':'06','julio':'07','agosto':'08',
    'septiembre':'09','octubre':'10','noviembre':'11','diciembre':'12'
}

# -------------------------------------------------------------
# FUNCIONES
# -------------------------------------------------------------
def get_soup(url, session):
    """Petición HTTP → BeautifulSoup. Retorna None si falla."""
    try:
        response = session.get(url, timeout=10)
        response.raise_for_status()
        return BeautifulSoup(response.text, 'html.parser')
    except requests.RequestException as e:
        print(f"  Error: {url} -> {e}")
        return None

def clean_text(text):
    """Elimina espacios y saltos de línea extra."""
    return re.sub(r'\s+', ' ', text).strip() if text else ""

def extract_article_data(soup):
    """
    Extrae título, fecha, sección y contenido del artículo.
    Estructura HTML de elnortehoycr.com:
      - Título:    <h1 class="entry-title">
      - Fecha:     <span class="published"> → "5 julio, 2023"
      - Sección:   <span class="ast-terms-link"><a>
      - Contenido: <div class="entry-content clear">
      - Nota: algunos artículos tienen contenido en tablas <figure>
    """
    # Título
    title_tag = soup.find('h1', class_='entry-title')
    title = clean_text(title_tag.get_text()) if title_tag else "Sin titulo"

    # Fecha — "5 julio, 2023" → YYYY-MM-DD
    date = "Sin fecha"
    date_span = soup.find('span', class_='published')
    if date_span:
        date_raw = clean_text(date_span.get_text())
        try:
            parts = date_raw.replace(',', '').split()
            mes = MESES.get(parts[1].lower(), '01')
            date = f"{parts[2]}-{mes}-{int(parts[0]):02d}"
        except:
            date = date_raw

    # Sección
    section = "sin-seccion"
    terms = soup.find('span', class_='ast-terms-link')
    if terms:
        a_tag = terms.find('a')
        if a_tag:
            section = clean_text(a_tag.get_text()).lower()
            section = section.replace('á','a').replace('é','e').replace('í','i').replace('ó','o').replace('ú','u').replace(' ','-')

    # Contenido — sin figure en decompose para capturar tablas
    content = "Contenido no encontrado"
    content_div = soup.find('div', class_=re.compile(r'entry-content'))
    if content_div:
        for tag in content_div.find_all(['script', 'style', 'iframe', 'aside']):
            tag.decompose()
        content = clean_text(content_div.get_text())

    return title, date, section, content

# -------------------------------------------------------------
# SCRAPING PRINCIPAL
# -------------------------------------------------------------
data = []
urls_vistas = set()

with requests.Session() as session:
    session.headers.update(HEADERS)

    for section, url in SECCIONES.items():
        print(f"\nSeccion: {section.upper()} -> {url}")
        main_soup = get_soup(url, session)
        if main_soup is None:
            print(f"  No se pudo acceder.")
            continue

        links = []
        for h2 in main_soup.find_all('h2', class_=re.compile(r'entry-title')):
            a = h2.find('a', href=True)
            if a and 'elnortehoycr.com' in a['href'] and a['href'] not in urls_vistas:
                links.append(a['href'])
                urls_vistas.add(a['href'])

        print(f"  {len(links)} articulos nuevos encontrados.")

        for i, link in enumerate(links, 1):
            print(f"    [{i}/{len(links)}] {link.split('/')[-2][:55]}...")
            time.sleep(DELAY)

            article_soup = get_soup(link, session)
            if article_soup:
                title, date, section_real, content = extract_article_data(article_soup)
            else:
                title, date, section_real, content = "Error", "Error", section, "Error al recuperar"

            data.append({
                'source':           'elnortehoycr',
                'url':              link,
                'title':            title,
                'publication_date': date,
                'scraping_date':    datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
                'section':          section_real,
                'full_text':        content,
                'language':         'es'
            })

# -------------------------------------------------------------
# RESULTADO FINAL
# -------------------------------------------------------------
df6 = pd.DataFrame(data)
print(f"\nDataFrame: {len(df6)} filas x {len(df6.columns)} columnas")
df6.head(8)

from google.colab import files
df6.to_csv('elnortehoycr.csv', index=False, encoding='utf-8', sep=',', na_rep='NULL')
files.download('elnortehoycr.csv')