# -*- coding: utf-8 -*-
"""Lanacion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TyPim-s_QRCyTMuZ8vv_xEymdXCDuLc1
"""

"""
scraper_nacion.py
=================
Scraper de noticias para La Nación (nacion.com)

Uso:
    python scraper_nacion.py

Salida: JSON y CSV con timestamp en el nombre del archivo.

Nota: La Nación tiene contenido de pago (paywall). Los artículos
      bajo suscripción devuelven texto parcial o vacío. El scraper
      extrae lo que esté disponible públicamente.

Dependencias:
    pip install requests beautifulsoup4 lxml
"""

import csv
import json
import re
import time
from datetime import datetime

import requests
from bs4 import BeautifulSoup

# ─────────────────────────────────────────────
#  CONFIGURACIÓN
# ─────────────────────────────────────────────
URL_BASE = "https://www.nacion.com/ultimas-noticias/"

HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/123.0.0.0 Safari/537.36"
    ),
    "Accept-Language": "es-CR,es;q=0.9",
}

DELAY = 1.5  # segundos entre requests

CAMPOS = [
    "source", "url", "title", "author",
    "publication_date", "scraping_date",
    "section", "full_text", "language",
]

# Clases CSS que indican ruido (ads, newsletter, share, etc.)
CLASES_RUIDO = {
    "ad", "ads", "advert", "advertisement",
    "paywall", "suscri", "subscribe", "newsletter",
    "related", "promo", "banner", "publicidad",
    "compartir", "share", "sidebar", "widget",
    "tag", "etiqueta", "author-bio", "bio",
    "comment", "footer", "header", "nav",
    "redes", "social", "popup",
}


# ─────────────────────────────────────────────
#  UTILIDADES
# ─────────────────────────────────────────────
def get_soup(url: str, timeout: int = 15) -> BeautifulSoup:
    resp = requests.get(url, headers=HEADERS, timeout=timeout)
    resp.raise_for_status()
    return BeautifulSoup(resp.text, "html.parser")


def abs_url(href: str) -> str:
    if not href:
        return ""
    if href.startswith("http"):
        return href
    if href.startswith("/"):
        return "https://www.nacion.com" + href
    return href


def limpiar_texto(contenedor: BeautifulSoup) -> str:
    """Extrae párrafos descartando bloques de ruido."""
    partes = []
    for tag in contenedor.find_all(["p", "h2", "h3", "h4", "blockquote"]):
        clases = " ".join(tag.get("class", [])).lower()
        if any(r in clases for r in CLASES_RUIDO):
            continue
        # Descartar si algún padre tiene clase de ruido
        padre_ruido = False
        for padre in tag.parents:
            p_clases = " ".join(padre.get("class", [])).lower() if padre.get("class") else ""
            if any(r in p_clases for r in CLASES_RUIDO):
                padre_ruido = True
                break
        if padre_ruido:
            continue
        texto = tag.get_text(separator=" ", strip=True)
        if texto and len(texto) > 25:
            partes.append(texto)
    return "\n\n".join(partes)


# ─────────────────────────────────────────────
#  LISTADO DE NOTICIAS
# ─────────────────────────────────────────────
def scrape_lista_noticias(url: str) -> list[dict]:
    """
    Extrae título, enlace, autor, fecha y sección
    de cada noticia en la sección de últimas noticias de nacion.com.

    La Nación usa Arc Publishing.
    Las URLs de artículos siguen el patrón /seccion/.../HASHID/story/
    """
    soup = get_soup(url)
    vistos = set()
    noticias = []

    # Patrón Arc Publishing: /seccion/subseccion/.../HASH/story/
    patron_noticia = re.compile(r"https://www\.nacion\.com/[^?#]+/story/")
    patron_rel     = re.compile(r"/[^?#]+/story/")

    for a in soup.find_all("a", href=True):
        href   = a["href"]
        enlace = abs_url(href)

        if not (patron_noticia.match(enlace) or patron_rel.match(href)):
            continue
        # Excluir URLs de videos, podcasts y brandvoice
        if any(x in enlace for x in ["/videos/", "/podcast/", "/brandvoice/", "/todobusco/"]):
            continue
        if enlace in vistos:
            continue

        # ── Título ───────────────────────────────────────────────────
        titulo = a.get_text(strip=True)
        if len(titulo) < 15:
            heading = (a.find_parent(["h1", "h2", "h3"]) or
                       a.find_next(["h1", "h2", "h3"]))
            if heading:
                titulo = heading.get_text(strip=True)
        if len(titulo) < 15:
            continue

        vistos.add(enlace)
        contenedor = a.find_parent(["article", "div", "section"]) or a

        # ── Fecha ────────────────────────────────────────────────────
        fecha_tag = (contenedor.select_one("time[datetime]") or
                     contenedor.select_one("span[class*='date']") or
                     contenedor.select_one("time"))
        if fecha_tag:
            fecha = fecha_tag.get("datetime", "") or fecha_tag.get_text(strip=True)
        else:
            fecha = "Sin fecha"

        # ── Sección desde URL ─────────────────────────────────────────
        partes_url = [p for p in enlace.replace("https://www.nacion.com", "").split("/") if p]
        seccion = partes_url[0].replace("-", " ").title() if partes_url else "Sin sección"

        # ── Autor ─────────────────────────────────────────────────────
        autor_tag = (contenedor.select_one("span[class*='author']") or
                     contenedor.select_one("a[class*='author']") or
                     contenedor.select_one("a[href*='/autor/']"))
        autor = autor_tag.get_text(strip=True) if autor_tag else ""

        noticias.append({
            "source":           "nacion.com",
            "url":              enlace,
            "title":            titulo,
            "author":           autor,
            "publication_date": fecha,
            "scraping_date":    datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            "section":          seccion,
            "full_text":        "",
            "language":         "es",
        })

    return noticias


# ─────────────────────────────────────────────
#  TEXTO DE CADA ARTÍCULO
# ─────────────────────────────────────────────
def scrape_texto_articulo(url: str) -> str:
    """
    Ingresa al artículo y extrae solo el cuerpo editorial,
    sin ads, newsletter, share buttons ni contenido relacionado.

    La Nación usa Arc Publishing: el contenido principal vive en
    divs con clase 'paragraph-body' o en bloques 'body-content'.
    Artículos de pago devuelven texto parcial.
    """
    if not url:
        return ""

    soup = get_soup(url)

    SELECTORES = [
        # Arc Publishing — selectores específicos
        "div.paragraph-body",
        "div[class*='paragraph-body']",
        "section.body-content",
        "div[class*='body-content']",
        "div[class*='story-body']",
        "div[class*='article-body']",
        # Fallbacks genéricos
        "div.entry-content",
        "article",
    ]

    for sel in SELECTORES:
        contenedor = soup.select_one(sel)
        if contenedor:
            ps = [p for p in contenedor.find_all("p") if len(p.get_text(strip=True)) > 40]
            if ps:
                return limpiar_texto(contenedor)

    # Diagnóstico automático si ningún selector funcionó
    print(f"\n⚠️  No se encontró cuerpo del artículo en: {url}")
    print("   Top 5 divs con más párrafos directos:")
    candidatos = []
    for div in soup.find_all("div"):
        ps = div.find_all("p", recursive=False)
        if len(ps) >= 3:
            clases = " ".join(div.get("class", [])) or "(sin clase)"
            candidatos.append((len(ps), clases))
    for cant, cls in sorted(candidatos, reverse=True)[:5]:
        print(f"     {cant} <p> → div clase: {cls}")

    # Fallback final
    partes = [p.get_text(strip=True) for p in soup.find_all("p")
              if len(p.get_text(strip=True)) > 60]
    return "\n\n".join(partes) if partes else "No se pudo extraer el contenido."


# ─────────────────────────────────────────────
#  ORQUESTADOR
# ─────────────────────────────────────────────
def scraper_completo(url: str) -> list[dict]:
    print(f"🔍 Obteniendo listado de noticias: {url}\n")
    noticias = scrape_lista_noticias(url)
    print(f"📰 {len(noticias)} noticias encontradas. Extrayendo contenido...\n")

    for i, n in enumerate(noticias, 1):
        print(f"  [{i}/{len(noticias)}] {n['title'][:70]}...")
        try:
            n["full_text"] = scrape_texto_articulo(n["url"])
        except Exception as e:
            n["full_text"] = f"Error al extraer: {e}"
        time.sleep(DELAY)

    return noticias


# ─────────────────────────────────────────────
#  GUARDAR RESULTADOS
# ─────────────────────────────────────────────
def guardar_json(noticias: list[dict], archivo: str) -> None:
    with open(archivo, "w", encoding="utf-8") as f:
        json.dump(noticias, f, ensure_ascii=False, indent=2)
    print(f"\n✅ JSON guardado en: {archivo}")


def guardar_csv(noticias: list[dict], archivo: str) -> None:
    with open(archivo, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=CAMPOS)
        writer.writeheader()
        writer.writerows(noticias)
    print(f"✅ CSV  guardado en: {archivo}")


def imprimir_resumen(noticias: list[dict]) -> None:
    print("\n" + "=" * 70)
    print("RESUMEN — La Nación")
    print("=" * 70)
    for i, n in enumerate(noticias, 1):
        print(f"\n{'─'*60}")
        print(f"[{i}] {n['title']}")
        if n.get("author"):
            print(f"    ✍️  {n['author']}")
        print(f"    📅 {n['publication_date']}")
        print(f"    🏷  {n['section']}")
        print(f"    🔗 {n['url']}")
        preview = n["full_text"][:200].replace("\n", " ")
        print(f"    📄 {preview}{'...' if len(n['full_text']) > 200 else ''}")


# ─────────────────────────────────────────────
#  MAIN
# ─────────────────────────────────────────────
if __name__ == "__main__":
    noticias = scraper_completo(URL_BASE)
    imprimir_resumen(noticias)

    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    guardar_json(noticias, f"noticias_nacion_{ts}.json")
    guardar_csv(noticias,  f"noticias_nacion_{ts}.csv")