# -*- coding: utf-8 -*-
"""Larepublica.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qkkr13z3Dq6TQ_kFmX9JVWqxCK2P5Cb9
"""

"""
scraper_larepublica.py
======================
Scraper de noticias para La República (larepublica.net)

Uso:
    python scraper_larepublica.py

Salida: JSON y CSV con timestamp en el nombre del archivo.

Dependencias:
    pip install requests beautifulsoup4 lxml
"""

import csv
import json
import re
import time
from datetime import datetime

import requests
from bs4 import BeautifulSoup

# ─────────────────────────────────────────────
#  CONFIGURACIÓN
# ─────────────────────────────────────────────
URL_BASE = "https://www.larepublica.net/"

HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/123.0.0.0 Safari/537.36"
    ),
    "Accept-Language": "es-CR,es;q=0.9",
}

DELAY = 1.5  # segundos entre requests

CAMPOS = [
    "source", "url", "title", "author",
    "publication_date", "scraping_date",
    "section", "full_text", "language",
]

# Clases CSS que indican ruido (ads, newsletter, share, etc.)
CLASES_RUIDO = {
    "ad", "ads", "advert", "advertisement",
    "paywall", "suscri", "subscribe", "newsletter",
    "related", "promo", "banner", "publicidad",
    "compartir", "share", "sidebar", "widget",
    "tag", "etiqueta", "author-bio", "bio",
    "comment", "footer", "header", "nav",
    "redes", "social", "popup",
}


# ─────────────────────────────────────────────
#  UTILIDADES
# ─────────────────────────────────────────────
def get_soup(url: str, timeout: int = 15) -> BeautifulSoup:
    resp = requests.get(url, headers=HEADERS, timeout=timeout)
    resp.raise_for_status()
    return BeautifulSoup(resp.text, "html.parser")


def abs_url(href: str) -> str:
    if not href:
        return ""
    if href.startswith("http"):
        return href
    if href.startswith("/"):
        return "https://www.larepublica.net" + href
    return href


def limpiar_texto(contenedor: BeautifulSoup) -> str:
    """Extrae párrafos descartando bloques de ruido."""
    partes = []
    for tag in contenedor.find_all(["p", "h2", "h3", "h4", "blockquote"]):
        clases = " ".join(tag.get("class", [])).lower()
        if any(r in clases for r in CLASES_RUIDO):
            continue
        # Descartar si algún padre tiene clase de ruido
        padre_ruido = False
        for padre in tag.parents:
            p_clases = " ".join(padre.get("class", [])).lower() if padre.get("class") else ""
            if any(r in p_clases for r in CLASES_RUIDO):
                padre_ruido = True
                break
        if padre_ruido:
            continue
        texto = tag.get_text(separator=" ", strip=True)
        if texto and len(texto) > 25:
            partes.append(texto)
    return "\n\n".join(partes)


# ─────────────────────────────────────────────
#  LISTADO DE NOTICIAS
# ─────────────────────────────────────────────
def scrape_lista_noticias(url: str) -> list[dict]:
    """
    Extrae título, enlace, autor, fecha y sección
    de cada noticia en la portada de larepublica.net.

    La República usa WordPress clásico.
    Las URLs de noticias tienen el patrón /noticia/<slug>.
    """
    soup = get_soup(url)
    vistos = set()
    noticias = []

    patron_noticia = re.compile(r"https://www\.larepublica\.net/noticia/.+")

    for a in soup.find_all("a", href=True):
        href   = a["href"]
        enlace = abs_url(href)

        # Normalizar: asegurar que termine sin barra doble
        if href.startswith("/noticia/"):
            enlace = "https://www.larepublica.net" + href

        if not patron_noticia.match(enlace):
            continue
        if enlace in vistos:
            continue

        # ── Título ───────────────────────────────────────────────────
        titulo = a.get_text(strip=True)
        if len(titulo) < 15:
            heading = (a.find_parent(["h1", "h2", "h3", "h4"]) or
                       a.find_next(["h1", "h2", "h3"]))
            if heading:
                titulo = heading.get_text(strip=True)
        if len(titulo) < 15:
            continue

        vistos.add(enlace)
        contenedor = a.find_parent(["article", "div"]) or a

        # ── Fecha ────────────────────────────────────────────────────
        fecha_tag = (contenedor.select_one("time[datetime]") or
                     contenedor.select_one("span[class*='date']") or
                     contenedor.select_one("time"))
        if fecha_tag:
            fecha = fecha_tag.get("datetime", "") or fecha_tag.get_text(strip=True)
        else:
            fecha = "Sin fecha"

        # ── Sección ──────────────────────────────────────────────────
        seccion_tag = contenedor.select_one("a[href*='/seccion/']")
        if seccion_tag:
            seccion = seccion_tag.get_text(strip=True).title()
        else:
            seccion = "Sin sección"

        # ── Autor ────────────────────────────────────────────────────
        autor_tag = (contenedor.select_one("a[href*='/autor/']") or
                     contenedor.select_one("span[class*='author']"))
        autor = autor_tag.get_text(strip=True) if autor_tag else ""

        noticias.append({
            "source":           "larepublica.net",
            "url":              enlace,
            "title":            titulo,
            "author":           autor,
            "publication_date": fecha,
            "scraping_date":    datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            "section":          seccion,
            "full_text":        "",
            "language":         "es",
        })

    return noticias


# ─────────────────────────────────────────────
#  TEXTO DE CADA ARTÍCULO
# ─────────────────────────────────────────────
def scrape_texto_articulo(url: str) -> str:
    """
    Ingresa al artículo y extrae solo el cuerpo editorial,
    sin ads, newsletter, share buttons ni contenido relacionado.
    """
    if not url:
        return ""

    soup = get_soup(url)

    SELECTORES = [
        "div.entry-content",
        "div.td-post-content",
        "div[class*='post-content']",
        "div[class*='article-body']",
        "article div[class*='content']",
        "article",
    ]

    for sel in SELECTORES:
        contenedor = soup.select_one(sel)
        if contenedor:
            ps = [p for p in contenedor.find_all("p") if len(p.get_text(strip=True)) > 40]
            if ps:
                return limpiar_texto(contenedor)

    # Fallback: todos los párrafos largos del documento
    partes = [p.get_text(strip=True) for p in soup.find_all("p")
              if len(p.get_text(strip=True)) > 60]
    return "\n\n".join(partes) if partes else "No se pudo extraer el contenido."


# ─────────────────────────────────────────────
#  ORQUESTADOR
# ─────────────────────────────────────────────
def scraper_completo(url: str) -> list[dict]:
    print(f"🔍 Obteniendo listado de noticias: {url}\n")
    noticias = scrape_lista_noticias(url)
    print(f"📰 {len(noticias)} noticias encontradas. Extrayendo contenido...\n")

    for i, n in enumerate(noticias, 1):
        print(f"  [{i}/{len(noticias)}] {n['title'][:70]}...")
        try:
            n["full_text"] = scrape_texto_articulo(n["url"])
        except Exception as e:
            n["full_text"] = f"Error al extraer: {e}"
        time.sleep(DELAY)

    return noticias


# ─────────────────────────────────────────────
#  GUARDAR RESULTADOS
# ─────────────────────────────────────────────
def guardar_json(noticias: list[dict], archivo: str) -> None:
    with open(archivo, "w", encoding="utf-8") as f:
        json.dump(noticias, f, ensure_ascii=False, indent=2)
    print(f"\n✅ JSON guardado en: {archivo}")


def guardar_csv(noticias: list[dict], archivo: str) -> None:
    with open(archivo, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=CAMPOS)
        writer.writeheader()
        writer.writerows(noticias)
    print(f"✅ CSV  guardado en: {archivo}")


def imprimir_resumen(noticias: list[dict]) -> None:
    print("\n" + "=" * 70)
    print("RESUMEN — La República")
    print("=" * 70)
    for i, n in enumerate(noticias, 1):
        print(f"\n{'─'*60}")
        print(f"[{i}] {n['title']}")
        if n.get("author"):
            print(f"    ✍️  {n['author']}")
        print(f"    📅 {n['publication_date']}")
        print(f"    🏷  {n['section']}")
        print(f"    🔗 {n['url']}")
        preview = n["full_text"][:200].replace("\n", " ")
        print(f"    📄 {preview}{'...' if len(n['full_text']) > 200 else ''}")


# ─────────────────────────────────────────────
#  MAIN
# ─────────────────────────────────────────────
if __name__ == "__main__":
    noticias = scraper_completo(URL_BASE)
    imprimir_resumen(noticias)

    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    guardar_json(noticias, f"noticias_larepublica_{ts}.json")
    guardar_csv(noticias,  f"noticias_larepublica_{ts}.csv")