# -*- coding: utf-8 -*-
"""Noticias La Garita Costa Rica.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11KUU22vQXyRBXCRL2EhRIg2p2GlueuQK
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd
import time
import re
import logging
from datetime import datetime

# --- Configuración ---
SECCIONES = {
    'nacionales':         'https://www.noticiaslagaritacr.com/category/nacionales/',
    'internacionales':    'https://www.noticiaslagaritacr.com/category/internacionales/',
    'sucesos':            'https://www.noticiaslagaritacr.com/category/sucesos/',
    'editorial':          'https://www.noticiaslagaritacr.com/category/editorial/',
    'turismo':            'https://www.noticiaslagaritacr.com/category/turismo/',
    'espectaculos':       'https://www.noticiaslagaritacr.com/category/nacionales/espectaculos/',
    'deportes':           'https://www.noticiaslagaritacr.com/category/deportes/',
    'ciencia-tecnologia': 'https://www.noticiaslagaritacr.com/category/ciencia-y-tecnologia/',
}
HEADERS = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 '
                  '(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
}
SOURCE    = 'noticiaslagarita'
DELAY     = 1.5
MIN_CHARS = 300
TODAY     = datetime.now().strftime('%Y%m%d')
OUT_FILE  = f'{SOURCE}_{TODAY}.csv'
LOG_FILE  = f'{SOURCE}_{TODAY}_descartados.log'

# --- Logging ---
logging.basicConfig(
    filename=LOG_FILE,
    level=logging.INFO,
    format='%(asctime)s | %(levelname)s | %(message)s',
    datefmt='%Y-%m-%d %H:%M:%S'
)
def log_descarte(url, motivo):
    logging.info(f"DESCARTADO | {motivo} | {url}")
def log_error(url, error):
    logging.error(f"ERROR | {error} | {url}")

# --- Funciones ---
def get_soup(url, session):
    """Petición HTTP → BeautifulSoup. Retorna None si falla."""
    try:
        response = session.get(url, timeout=10)
        response.raise_for_status()
        return BeautifulSoup(response.text, 'html.parser')
    except requests.RequestException as e:
        log_error(url, str(e))
        print(f"  ⚠️  Error: {url} → {e}")
        return None

def clean_text(text):
    """Elimina espacios/saltos de línea extra."""
    return re.sub(r'\s+', ' ', text).strip() if text else ""

def extract_article_data(soup):
    """
    Extrae título, fecha y contenido desde la página interna del artículo.
    Selectores basados en la estructura real de noticiaslagaritacr.com:
      - Título:    <h1 class="title"> dentro de <div class="mg-header">
      - Fecha:     <meta property="article:published_time"> → YYYY-MM-DD
      - Contenido: <article class="small single">
    """
    # --- Título ---
    title = None
    mg_header = soup.find('div', class_='mg-header')
    if mg_header:
        h1 = mg_header.find('h1', class_='title')
        if h1:
            title = clean_text(h1.get_text())

    # --- Fecha ---
    date = None
    meta_date = soup.find('meta', property='article:published_time')
    if meta_date:
        date = meta_date.get('content', '')[:10]  # YYYY-MM-DD

    # --- Contenido ---
    content = None
    article_tag = soup.find('article', class_='small single')
    if article_tag:
        for tag in article_tag.find_all(['script', 'style', 'iframe',
                                         'figure', 'nav', 'aside']):
            tag.decompose()
        for div in article_tag.find_all('div', class_=re.compile(r'post-share|gallery')):
            div.decompose()
        content = clean_text(article_tag.get_text())

    return title, date, content

# -------------------------------------------------------
# PASO 1: Leer listado → extraer enlaces desde h4.title
# -------------------------------------------------------
data = []
urls_vistas = set()

with requests.Session() as session:
    session.headers.update(HEADERS)

    for section, base_url in SECCIONES.items():
        print(f"\n📂 Sección: {section.upper()} → {base_url}")
        main_soup = get_soup(base_url, session)

        if main_soup is None:
            print("  ❌ No se pudo acceder a la sección.")
            continue

        # ✅ Selector correcto: <h4 class="title"> en la página de categoría
        title_tags = main_soup.find_all('h4', class_='title')
        print(f"  ✅ {len(title_tags)} noticias encontradas.\n")

        # -------------------------------------------------------
        # PASO 2: Entrar a cada enlace y extraer datos del artículo
        # -------------------------------------------------------
        for i, h4 in enumerate(title_tags, 1):
            a_tag = h4.find('a', href=True)
            if not a_tag:
                continue

            link = a_tag['href']
            if link in urls_vistas:
                continue
            urls_vistas.add(link)

            print(f"  [{i}/{len(title_tags)}] {link.split('/')[-2][:60]}...")
            time.sleep(DELAY)

            article_soup = get_soup(link, session)
            if not article_soup:
                continue

            title, date, content = extract_article_data(article_soup)

            # --- Validaciones obligatorias (estándar sección 6) ---
            if not date:
                log_descarte(link, "publication_date nulo")
                continue

            if not content or len(content) < MIN_CHARS:
                log_descarte(link, f"full_text < {MIN_CHARS} chars ({len(content) if content else 0})")
                continue

            data.append({
                'source':           SOURCE,
                'url':              link,
                'title':            title,
                'publication_date': date,
                'scraping_date':    datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
                'section':          section,
                'full_text':        content,
                'language':         'es'
            })

# -------------------------------------------------------
# PASO 3: DataFrame final + exportación
# -------------------------------------------------------
df_garita = pd.DataFrame(data)

# Dedup por URL
antes = len(df_garita)
df_garita = df_garita.drop_duplicates(subset='url', keep='first')
print(f"\n🔁 Duplicados eliminados: {antes - len(df_garita)}")

# Nulos como NULL real
df_garita = df_garita.where(pd.notnull(df_garita), other=None)

# Exportar — UTF-8, sin índice, source_YYYYMMDD.csv
df_garita.to_csv(OUT_FILE, index=False, encoding='utf-8', na_rep='NULL')

print(f"💾 Archivo exportado: {OUT_FILE}")
print(f"📋 Log de descartes:  {LOG_FILE}")
print(f"📊 DataFrame final:   {len(df_garita)} filas x {len(df_garita.columns)} columnas")
df_garita.head(8)

from google.colab import files
df_garita.to_csv(OUT_FILE, index=False, encoding='utf-8', sep=',', na_rep='NULL')
files.download(OUT_FILE)