# -*- coding: utf-8 -*-
"""Periodico el mundo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cPsl_WzlSHxIGxQQzkVan4twnW8zRH41
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd
import time
import re
from datetime import datetime

# --- Configuración ---
BASE_URL = 'https://elmundo.cr/costa-rica/'
HEADERS = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 '
                  '(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
}
DELAY = 1.0

def get_soup(url, session):
    """Petición HTTP → BeautifulSoup. Retorna None si falla."""
    try:
        response = session.get(url, timeout=10)
        response.raise_for_status()
        return BeautifulSoup(response.text, 'html.parser')
    except requests.RequestException as e:
        print(f"  ⚠️  Error: {url} → {e}")
        return None

def clean_text(text):
    """Elimina espacios/saltos de línea extra."""
    return re.sub(r'\s+', ' ', text).strip() if text else ""

def extract_article_data(soup):
    """
    Extrae título, fecha y contenido desde la página interna del artículo.
    Selectores basados en la estructura real de elmundo.cr
    """
    # --- Título ---
    # <h1 class="elementor-heading-title elementor-size-default">
    title_tag = soup.find('h1', class_='elementor-heading-title')
    title = clean_text(title_tag.get_text()) if title_tag else "Sin título"

    # --- Fecha ---
    # <span class="...elementor-post-info__item--type-date"><time>marzo 20, 2026</time></span>
    date_span = soup.find('span', class_='elementor-post-info__item--type-date')
    if date_span:
        time_tag = date_span.find('time')
        date = clean_text(time_tag.get_text()) if time_tag else clean_text(date_span.get_text())
    else:
        date = "Sin fecha"

    # --- Contenido ---
    # <div class="elementor-widget-theme-post-content">
    #     <div class="elementor-widget-container"> ← texto aquí
    content_div = soup.find('div', class_='elementor-widget-theme-post-content')
    if content_div:
        container = content_div.find('div', class_='elementor-widget-container')
        target = container if container else content_div

        # Eliminar scripts, estilos y bloques de anuncios
        for tag in target.find_all(['script', 'style', 'iframe', 'figure']):
            tag.decompose()
        for ad in target.find_all('div', class_='code-block'):
            ad.decompose()

        content = clean_text(target.get_text())
    else:
        content = "Contenido no encontrado"

    return title, date, content

# -------------------------------------------------------
# PASO 1: Leer listado → extraer enlace desde h3.elementor-post__title
# -------------------------------------------------------
data = []

with requests.Session() as session:
    session.headers.update(HEADERS)

    print(f"📰 Leyendo listado de noticias: {BASE_URL}\n")
    main_soup = get_soup(BASE_URL, session)

    if main_soup is None:
        print("❌ No se pudo acceder a la página principal.")
    else:
        title_tags = main_soup.find_all('h3', class_='elementor-post__title')
        print(f"✅ {len(title_tags)} noticias encontradas.\n")

        # -------------------------------------------------------
        # PASO 2: Entrar a cada enlace y extraer datos del artículo
        # -------------------------------------------------------
        for i, h3 in enumerate(title_tags, 1):
            a_tag = h3.find('a', href=True)
            if not a_tag:
                continue

            link = a_tag['href']
            print(f"  [{i}/{len(title_tags)}] Procesando: {link.split('/')[-2][:60]}...")
            time.sleep(DELAY)

            article_soup = get_soup(link, session)
            if article_soup:
                title, date, content = extract_article_data(article_soup)
            else:
                title, date, content = "Error", "Error", "Error al recuperar"

            data.append({
    'source':           'elmundocr',                          # minúsculas, sin espacios ni tildes
    'url':              link,                                  # URL única del artículo
    'title':            title,                                 # titular limpio
    'publication_date': date,                                  # (ya lo extraes, falta parsear a YYYY-MM-DD)
    'scraping_date':    datetime.now().strftime('%Y-%m-%d %H:%M:%S'),  # momento de extracción
    'section':          'costa-rica',                          # sección del medio
    'full_text':        content,                               # cuerpo limpio
    'language':         'es'                                   # código ISO
})

# -------------------------------------------------------
# PASO 3: DataFrame final
# -------------------------------------------------------
df1 = pd.DataFrame(data)

pd.set_option('display.max_colwidth', 80)
print(f"\n📊 DataFrame: {len(df1)} filas × {len(df1.columns)} columnas")
df1.head(8)

df1.to_csv('elmundocr.csv', index=False)
print("Archivo guardado correctamente.")