# -*- coding: utf-8 -*-
"""SanCarlosDigital.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c2n6TPXKwz4OGmlMMrpjjhoIgUyRxKx3

Paginación limitada en sancarlosdigital.com
# El sitio muestra solo los primeros artículos visibles en cada sección.
# Existe un botón "Cargar más" que carga artículos adicionales mediante JavaScript,
# por lo que BeautifulSoup no puede acceder a ellos sin Selenium.
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd
import re
import time
from datetime import datetime

# -------------------------------------------------------------
# CONFIGURACIÓN
# -------------------------------------------------------------
SECCIONES = {
    'locales':    'https://sancarlosdigital.com/actualidad/locales/',
    'politica':   'https://sancarlosdigital.com/actualidad/politica/',
    'policiales': 'https://sancarlosdigital.com/actualidad/judiciales/',
}

HEADERS = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'}
DELAY = 1.5

# -------------------------------------------------------------
# FUNCIONES
# -------------------------------------------------------------
def get_soup(url, session):
    try:
        response = session.get(url, timeout=10)
        response.raise_for_status()
        return BeautifulSoup(response.text, 'html.parser')
    except requests.RequestException as e:
        print(f"  Error: {url} -> {e}")
        return None

def clean_text(text):
    return re.sub(r'\s+', ' ', text).strip() if text else ""

def extract_article_data(soup):
    # Título
    title_tag = soup.find('h1', class_='tdb-title-text')
    title = clean_text(title_tag.get_text()) if title_tag else "Sin titulo"

    # Fecha
    date = "Sin fecha"
    time_tag = soup.find('time', class_=re.compile(r'entry-date'))
    if time_tag:
        dt = time_tag.get('datetime', '')
        date = dt[:10] if dt else clean_text(time_tag.get_text())

    # Contenido
    content = "Contenido no encontrado"
    content_div = soup.find('div', class_=re.compile(r'td-post-content'))
    if content_div:
        for tag in content_div.find_all(['script', 'style', 'iframe', 'aside']):
            tag.decompose()
        content = clean_text(content_div.get_text())

    return title, date, content

# -------------------------------------------------------------
# SCRAPING PRINCIPAL
# -------------------------------------------------------------
data = []
urls_vistas = set()

with requests.Session() as session:
    session.headers.update(HEADERS)

    for section, url in SECCIONES.items():
        print(f"\nSeccion: {section.upper()} -> {url}")
        main_soup = get_soup(url, session)
        if main_soup is None:
            print(f"  No se pudo acceder.")
            continue

        links = []
        for h3 in main_soup.find_all('h3', class_=re.compile(r'entry-title|td-module-title')):
            a = h3.find('a', href=True)
            if a and 'sancarlosdigital.com' in a['href'] and a['href'] not in urls_vistas:
                links.append(a['href'])
                urls_vistas.add(a['href'])

        print(f"  {len(links)} articulos nuevos encontrados.")

        for i, link in enumerate(links, 1):
            print(f"    [{i}/{len(links)}] {link.split('/')[-2][:55]}...")
            time.sleep(DELAY)

            article_soup = get_soup(link, session)
            if article_soup:
                title, date, content = extract_article_data(article_soup)
            else:
                title, date, content = "Error", "Error", "Error al recuperar"

            data.append({
                'source':           'sancarlosdigital',
                'url':              link,
                'title':            title,
                'publication_date': date,
                'scraping_date':    datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
                'section':          section,  # directo del diccionario
                'full_text':        content,
                'language':         'es'
            })

# -------------------------------------------------------------
# RESULTADO FINAL
# -------------------------------------------------------------
df8 = pd.DataFrame(data)
print(f"\nDataFrame: {len(df8)} filas x {len(df8.columns)} columnas")
df8.head(8)

try:
    from google.colab import files
except ImportError:
    files = None
df8.to_csv('sancarlosdigital.csv', index=False, encoding='utf-8', sep=',', na_rep='NULL')
files.download('sancarlosdigital.csv')