# -*- coding: utf-8 -*-
"""seminario.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z5ohxjXcY28fm0ougZfB8VylfC61Qwnm

SOLO PAGINA PRINCIPAL
"""

# Instalar librería necesaria (solo si no está instalada)
!pip install ftfy

import requests
from bs4 import BeautifulSoup
import ftfy
import pandas as pd

# URL de El Financiero Costa Rica
url = "https://www.elfinancierocr.com/"

# Obtener el HTML
response = requests.get(url)
response.encoding = "utf-8"
html = response.text

# Parsear con BeautifulSoup
soup = BeautifulSoup(html, "html.parser")

# Extraer SOLO encabezados (evita duplicados por <a>)
headline_tags = soup.find_all(["h1", "h2", "h3"])

# Usar set para evitar duplicados desde el inicio
cleaned_titles = set()

for tag in headline_tags:
    text = tag.get_text(strip=True)

    # Filtros de longitud para evitar menús y textos basura
    if 40 < len(text) < 200:
        cleaned = ftfy.fix_text(text)
        cleaned_titles.add(cleaned)

# Convertir a DataFrame
df = pd.DataFrame(sorted(cleaned_titles), columns=["Titulares"])

# Guardar en CSV
df.to_csv("titulares_elfinanciero.csv", index=False, encoding="utf-8-sig")

print("Archivo generado correctamente: titulares_elfinanciero.csv")
print(f"Total de titulares únicos: {len(df)}")

"""TODAS LAS SECCIONES"""

import requests
from bs4 import BeautifulSoup
import pandas as pd
import re
import time
from datetime import datetime

SECCIONES = {
    'pais':          'https://semanariouniversidad.com/pais/',
    'universitarias':'https://semanariouniversidad.com/universitarias/',
    'mundo':         'https://semanariouniversidad.com/mundo/',
    'cultura':       'https://semanariouniversidad.com/cultura/',
    'tecnologia':    'https://semanariouniversidad.com/tecnologia/',
    'deportes':      'https://semanariouniversidad.com/deportes/',
    'opinion':       'https://semanariouniversidad.com/opinion/',
}

HEADERS = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 '
                  '(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
}
DELAY = 1.5

MESES = {
    'enero':'01','febrero':'02','marzo':'03','abril':'04',
    'mayo':'05','junio':'06','julio':'07','agosto':'08',
    'septiembre':'09','octubre':'10','noviembre':'11','diciembre':'12'
}

def get_soup(url, session):
    try:
        response = session.get(url, timeout=10)
        response.raise_for_status()
        return BeautifulSoup(response.text, 'html.parser')
    except requests.RequestException as e:
        print(f"  ⚠️  Error: {url} → {e}")
        return None

def clean_text(text):
    return re.sub(r'\s+', ' ', text).strip() if text else ""

def parse_date(raw_date):
    try:
        parts = raw_date.replace(',', '').split()
        mes = MESES.get(parts[1].lower(), '01')
        return f"{parts[2]}-{mes}-{int(parts[0]):02d}"
    except:
        return raw_date

def extract_content(soup):
    content = "Contenido no encontrado"
    entry = soup.find('div', class_='entry-content')
    if entry:
        contenido = entry.find('div', class_='contenido-textual')
        target = contenido if contenido else entry
        for tag in target.find_all(['script', 'style', 'iframe', 'figure']):
            tag.decompose()
        content = clean_text(target.get_text())
    return content

data = []

with requests.Session() as session:
    session.headers.update(HEADERS)

    for section, url in SECCIONES.items():
        print(f"\n📰 Sección: {section.upper()} → {url}")
        main_soup = get_soup(url, session)
        if main_soup is None:
            print(f"  ❌ No se pudo acceder.")
            continue

        articles = main_soup.find_all('article')
        print(f"  ✅ {len(articles)} artículos encontrados.")

        for i, article in enumerate(articles, 1):
            heading = article.find(['h1','h2','h3','h4','h5','h6'])
            title = clean_text(heading.get_text()) if heading else "Sin título"

            a_tag = article.find('a', href=True)
            link = a_tag['href'] if a_tag else None
            if not link:
                continue

            date_tag = article.find('time')
            date_raw = clean_text(date_tag.get_text()) if date_tag else "Sin fecha"

            print(f"    [{i}/{len(articles)}] {title[:55]}...")
            time.sleep(DELAY)

            article_soup = get_soup(link, session)
            content = extract_content(article_soup) if article_soup else "Error al recuperar"

            data.append({
                'source':           'semanariouniversidad',
                'url':              link,
                'title':            title,
                'publication_date': parse_date(date_raw),
                'scraping_date':    datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
                'section':          section,
                'full_text':        content,
                'language':         'es'
            })

df2 = pd.DataFrame(data)
print(f"\n📊 DataFrame final: {len(df2)} filas × {len(df2.columns)} columnas")
df2.head(10)

df2.to_csv('semanariouniversidad.csv', index=False, encoding='utf-8', sep=',', na_rep='NULL')